### ISSUE TITLE
develop: rust-analyzer panics upon usage of `StateStore` trait

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#1597]
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates/hir_ty/src/utils.rs:308:18
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: hir_ty::utils::Generics::find_param
   4: hir_ty::lower::TyLoweringContext::lower_partly_resolved_path
   5: hir_ty::lower::TyLoweringContext::lower_ty_ext
   6: hir_ty::lower::TyLoweringContext::substs_from_path_segment
   7: hir_ty::lower::TyLoweringContext::lower_trait_ref_from_path
   8: hir_ty::lower::TyLoweringContext::lower_type_bound
   9: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  10: <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
  11: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  12: hir_ty::chalk_db::associated_ty_data_query
  13: salsa::runtime::Runtime::execute_query_implementation
  14: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: salsa::QueryTable<Q>::get
  17: <DB as hir_ty::db::HirDatabase>::associated_ty_data
  18: <chalk_solve::clauses::env_elaborator::EnvElaborator<I> as chalk_ir::visit::Visitor<I>>::visit_domain_goal
  19: chalk_solve::clauses::env_elaborator::elaborate_env_clauses
  20: chalk_solve::clauses::program_clauses_for_env
  21: hir_ty::chalk_db::program_clauses_for_chalk_env_query
  22: salsa::runtime::Runtime::execute_query_implementation
  23: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  24: salsa::derived::slot::Slot<Q,MP>::read
  25: salsa::QueryTable<Q>::get
  26: <DB as hir_ty::db::HirDatabase>::program_clauses_for_chalk_env
  27: chalk_recursive::solve::SolveIteration::solve_iteration
  28: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  29: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  30: <hir_ty::db::TraitSolveQueryQuery as salsa::plumbing::QueryFunction>::execute
  31: salsa::runtime::Runtime::execute_query_implementation
  32: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  33: salsa::derived::slot::Slot<Q,MP>::read
  34: salsa::QueryTable<Q>::get
  35: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  36: hir_ty::db::trait_solve_wait
  37: <DB as hir_ty::db::HirDatabase>::trait_solve
  38: hir_ty::infer::unify::InferenceTable::try_obligation
  39: hir_ty::autoderef::autoderef_step
  40: <hir_ty::autoderef::Autoderef as core::iter::traits::iterator::Iterator>::next
  41: hir_ty::method_resolution::autoderef_method_receiver
  42: hir_ty::method_resolution::iterate_method_candidates_dyn
  43: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  44: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  45: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  46: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  47: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  48: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  49: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  50: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  51: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  52: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  53: hir_ty::infer::infer_query
  54: salsa::runtime::Runtime::execute_query_implementation
  55: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  56: salsa::derived::slot::Slot<Q,MP>::read
  57: salsa::QueryTable<Q>::get
  58: <DB as hir_ty::db::HirDatabase>::infer_query
  59: hir_ty::db::infer_wait
  60: hir::source_analyzer::SourceAnalyzer::new_for_body
  61: hir::semantics::SemanticsImpl::analyze_impl
  62: ide_db::defs::NameClass::classify
  63: ide::syntax_highlighting::highlight::name_like
  64: ide::syntax_highlighting::highlight
  65: std::panicking::try
  66: rust_analyzer::handlers::handle_semantic_tokens_range
  67: std::panicking::try
  68: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 1:07:43 PM] Request textDocument/semanticTokens/range failed.
  Message: server panicked: called `Option::unwrap()` on a `None` value
  Code: -32603 
Panic context:
> 
version: 2366d8e05 2022-04-06 nightly
request: experimental/inlayHints InlayHintsParams {
    text_document: TextDocumentIdentifier {
        uri: Url {
            scheme: "file",
            cannot_be_a_base: false,
            username: "",
            password: None,
            host: None,
            port: None,
            path: "/Users/skyzh/Work/risingwave/src/stream/src/executor/local_simple_agg.rs",
            query: None,
            fragment: None,
        },
    },
    range: Some(
        Range {
            start: Position {
                line: 48,
                character: 0,
            },
            end: Position {
                line: 164,
                character: 0,
            },
        },
    ),
}

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', crates/hir_ty/src/utils.rs:308:18
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: hir_ty::utils::Generics::find_param
   4: hir_ty::lower::TyLoweringContext::lower_partly_resolved_path
   5: hir_ty::lower::TyLoweringContext::lower_ty_ext
   6: hir_ty::lower::TyLoweringContext::substs_from_path_segment
   7: hir_ty::lower::TyLoweringContext::lower_trait_ref_from_path
   8: hir_ty::lower::TyLoweringContext::lower_type_bound
   9: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
  10: <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
  11: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  12: hir_ty::chalk_db::associated_ty_data_query
  13: salsa::runtime::Runtime::execute_query_implementation
  14: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  15: salsa::derived::slot::Slot<Q,MP>::read
  16: salsa::QueryTable<Q>::get
  17: <DB as hir_ty::db::HirDatabase>::associated_ty_data
  18: <chalk_solve::clauses::env_elaborator::EnvElaborator<I> as chalk_ir::visit::Visitor<I>>::visit_domain_goal
  19: chalk_solve::clauses::env_elaborator::elaborate_env_clauses
  20: chalk_solve::clauses::program_clauses_for_env
  21: hir_ty::chalk_db::program_clauses_for_chalk_env_query
  22: salsa::runtime::Runtime::execute_query_implementation
  23: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  24: salsa::derived::slot::Slot<Q,MP>::read
  25: salsa::QueryTable<Q>::get
  26: <DB as hir_ty::db::HirDatabase>::program_clauses_for_chalk_env
  27: chalk_recursive::solve::SolveIteration::solve_iteration
  28: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_goal
  29: chalk_recursive::fixed_point::RecursiveContext<K,V>::solve_root_goal
  30: <hir_ty::db::TraitSolveQueryQuery as salsa::plumbing::QueryFunction>::execute
  31: salsa::runtime::Runtime::execute_query_implementation
  32: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  33: salsa::derived::slot::Slot<Q,MP>::read
  34: salsa::QueryTable<Q>::get
  35: <DB as hir_ty::db::HirDatabase>::trait_solve_query
  36: hir_ty::db::trait_solve_wait
  37: <DB as hir_ty::db::HirDatabase>::trait_solve
  38: hir_ty::infer::unify::InferenceTable::try_obligation
  39: hir_ty::autoderef::autoderef_step
  40: <hir_ty::autoderef::Autoderef as core::iter::traits::iterator::Iterator>::next
  41: hir_ty::method_resolution::autoderef_method_receiver
  42: hir_ty::method_resolution::iterate_method_candidates_dyn
  43: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  44: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  45: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  46: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr
  47: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  48: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  49: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  50: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_block
  51: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_inner
  52: hir_ty::infer::expr::<impl hir_ty::infer::InferenceContext>::infer_expr_coerce
  53: hir_ty::infer::infer_query
  54: salsa::runtime::Runtime::execute_query_implementation
  55: salsa::derived::slot::Slot<Q,MP>::read_upgrade
  56: salsa::derived::slot::Slot<Q,MP>::read
  57: salsa::QueryTable<Q>::get
  58: <DB as hir_ty::db::HirDatabase>::infer_query
  59: hir_ty::db::infer_wait
  60: hir::source_analyzer::SourceAnalyzer::new_for_body
  61: hir::semantics::SemanticsImpl::analyze_impl
  62: hir::semantics::SemanticsImpl::type_of_pat
  63: ide::inlay_hints::hints
  64: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  65: ide::inlay_hints::inlay_hints
  66: std::panicking::try
  67: rust_analyzer::handlers::handle_inlay_hints
  68: std::panicking::try
  69: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Still finding ways to solve this... Hurts development a lot 🤪

**Comment by skyzh** [comment]
Also we can set

```
"editor.semanticHighlighting.enabled": false,
```

in workspace settings so as to bypass this issue...
