### ISSUE TITLE
bug: Panic when selecting from non-materialized source

### ISSUE THREAD

**Issue by hzxa21** [singularity-data/risingwave#1800]
**Describe the bug**
With rust frontend, select from non-materialized source cause frontend node to crash.

**To Reproduce**
```
patrick=> CREATE SOURCE kafka1 (v1 int, v2 varchar) with ('connector'='kafka', 'kafka.topic'='kafka_1_partition_mv_topic', 'kafka.broker'='127.0.0.1:29092', 'kafka.scan.startup.mode'='earliest', 'kafka.consumer.group'='kafka1-c1') ROW FORMAT JSON;
CREATE_SOURCE

patrick=> SELECT * FROM kafka1;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

**Expected behavior**
Return an error instead of panic

**Additional context**
frontend log:
```
thread 'tokio-runtime-worker' panicked at 'there is no batch source operator', src/frontend/src/optimizer/plan_node/logical_source.rs:94:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f4a7ce997a1d7546d2b737f8b87d36907bcea2ad/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/f4a7ce997a1d7546d2b737f8b87d36907bcea2ad/library/core/src/panicking.rs:142:14
   2: <risingwave_frontend::optimizer::plan_node::logical_source::LogicalSource as risingwave_frontend::optimizer::plan_node::convert::ToBatch>::to_batch
             at ./src/frontend/src/optimizer/plan_node/logical_source.rs:94:9
   3: <risingwave_frontend::optimizer::plan_node::logical_project::LogicalProject as risingwave_frontend::optimizer::plan_node::convert::ToBatch>::to_batch
             at ./src/frontend/src/optimizer/plan_node/logical_project.rs:272:25
   4: risingwave_frontend::optimizer::plan_node::convert::ToBatch::to_batch_with_order_required
             at ./src/frontend/src/optimizer/plan_node/convert.rs:66:19
   5: risingwave_frontend::optimizer::PlanRoot::gen_batch_query_plan
             at ./src/frontend/src/optimizer/mod.rs:149:16
   6: risingwave_frontend::handler::query_single::handle_query_single::{{closure}}
             at ./src/frontend/src/handler/query_single.rs:41:20
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f4a7ce997a1d7546d2b737f8b87d36907bcea2ad/library/core/src/future/mod.rs:91:19
   8: risingwave_frontend::handler::handle::{{closure}}
             at ./src/frontend/src/handler/mod.rs:79:65
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f4a7ce997a1d7546d2b737f8b87d36907bcea2ad/library/core/src/future/mod.rs:91:19
  10: <risingwave_frontend::session::SessionImpl as pgwire::pg_server::Session>::run_statement::{{closure}}
             at ./src/frontend/src/session.rs:382:37
```

**Comment by skyzh** [comment]
We don't support select from source for now. We should create materialized source.

**Comment by hzxa21** [comment]
> We don't support select from source for now. We should create materialized source.

Right. But we should return an error instead of panic.

**Comment by TszKitLo40** [comment]
I want to try this issue and new to rust. The panic is thrown in `to_batch(&self) -> PlanRef` in `logical_source.rs`, but the return value of this method is `Rc`, how can we return an error?

**Comment by liurenjie1024** [comment]
> I want to try this issue and new to rust. The panic is thrown in `to_batch(&self) -> PlanRef` in `logical_source.rs`, but the return value of this method is `Rc`, how can we return an error?

I think the correct way to resolve this is to deny such statement in binder, rather in planner.

**Comment by TszKitLo40** [comment]
> > I want to try this issue and new to rust. The panic is thrown in `to_batch(&self) -> PlanRef` in `logical_source.rs`, but the return value of this method is `Rc`, how can we return an error?
> 
> I think the correct way to resolve this is to deny such statement in binder, rather in planner.

Do you mean we should check whether the source of the Query can be batched in `bind_query`?

**Comment by liurenjie1024** [comment]
Yes.

**Comment by hzxa21** [comment]
This bug has been fixed.
