### ISSUE TITLE
bug: 'index out of bounds: the len is 1 but the index is 1', src/batch/src/task/task_.rs:281:24

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#2490]
**Describe the bug**

```
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 1 but the index is 1', src/batch/src/task/task_.rs:281:24
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_bounds_check
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/panicking.rs:84:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index_mut
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/slice/index.rs:248:14
   4: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/slice/index.rs:30:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/alloc/src/vec/mod.rs:2603:9
   6: risingwave_batch::task::task_::BatchTaskExecution::get_task_output
             at ./src/batch/src/task/task_.rs:281:24
   7: risingwave_batch::task::task_manager::BatchManager::take_output
             at ./src/batch/src/task/task_manager.rs:69:9
   8: risingwave_compute::rpc::service::exchange_service::ExchangeServiceImpl::get_data_impl::{{closure}}
             at ./src/compute/src/rpc/service/exchange_service.rs:119:31
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/future/mod.rs:91:19
  10: <risingwave_compute::rpc::service::exchange_service::ExchangeServiceImpl as risingwave_pb::task_service::exchange_service_server::ExchangeService>::get_data::{{closure}}
             at ./src/compute/src/rpc/service/exchange_service.rs:64:14
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/future/mod.rs:91:19
  12: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/future/future.rs:124:9
  13: <<risingwave_pb::task_service::exchange_service_server::ExchangeServiceServer<T> as tower_service::Service<http::request::Request<B>>>::call::GetDataSvc<T> as tonic::server::service::ServerStreamingService<risingwave_pb::task_service::GetDataRequest>>::call::{{closure}}
             at ./src/prost/src/task_service.rs:666:78
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/future/mod.rs:91:19
  15: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/future/future.rs:124:9
  16: tonic::server::grpc::Grpc<T>::server_streaming::{{closure}}
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.7.2/src/server/grpc.rs:246:45
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/future/mod.rs:91:19
  18: <risingwave_pb::task_service::exchange_service_server::ExchangeServiceServer<T> as tower_service::Service<http::request::Request<B>>>::call::{{closure}}
             at ./src/prost/src/task_service.rs:682:69
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/future/mod.rs:91:19
  20: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/future/future.rs:124:9
  21: <F as futures_core::future::TryFuture>::try_poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/future.rs:82:9
  22: <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/try_future/into_future.rs:34:9
  23: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/future/map.rs:55:37
  24: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/lib.rs:91:13
  25: <futures_util::future::try_future::MapOk<Fut,F> as core::future::future::Future>::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/lib.rs:91:13
  26: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.12/src/macros.rs:38:17
  27: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/future/future.rs:124:9
  28: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.12/src/util/oneshot.rs:97:38
  29: <axum::routing::route::RouteFuture<B,E> as core::future::future::Future>::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.5.4/src/routing/route.rs:150:61
  30: <tonic::transport::service::router::RoutesFuture as core::future::future::Future>::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.7.2/src/transport/service/router.rs:90:36
  31: <tonic::transport::service::grpc_timeout::ResponseFuture<F> as core::future::future::Future>::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.7.2/src/transport/service/grpc_timeout.rs:88:38
  32: <tower::util::either::Either<A,B> as core::future::future::Future>::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tower-0.4.12/src/util/either.rs:71:57
  33: <tonic::transport::server::recover_error::ResponseFuture<F> as core::future::future::Future>::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.7.2/src/transport/server/recover_error.rs:63:20
  34: <tonic::transport::server::SvcFuture<F> as core::future::future::Future>::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tonic-0.7.2/src/transport/server/mod.rs:757:50
  35: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/future/future.rs:124:9
  36: hyper::proto::h2::server::H2Stream<F,B>::poll2
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.18/src/proto/h2/server.rs:448:37
  37: <hyper::proto::h2::server::H2Stream<F,B> as core::future::future::Future>::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.18/src/proto/h2/server.rs:537:9
  38: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:165:17
  39: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/loom/std/unsafe_cell.rs:14:9
  40: tokio::runtime::task::core::CoreStage<T>::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:155:13
  41: tokio::runtime::task::harness::poll_future::{{closure}}
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:470:19
  42: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/panic/unwind_safe.rs:271:9
  43: std::panicking::try::do_call
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panicking.rs:492:40
  44: __rust_try
  45: std::panicking::try
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panicking.rs:456:19
  46: std::panic::catch_unwind
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panic.rs:137:14
  47: tokio::runtime::task::harness::poll_future
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:458:18
  48: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:104:27
  49: tokio::runtime::task::harness::Harness<T,S>::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:57:15
  50: tokio::runtime::task::raw::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:144:5
  51: tokio::runtime::task::raw::RawTask::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:84:18
  52: tokio::runtime::task::LocalNotified<S>::run
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/mod.rs:376:9
  53: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:454:21
  54: tokio::coop::with_budget::{{closure}}
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:102:9
  55: std::thread::local::LocalKey<T>::try_with
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/thread/local.rs:445:16
  56: std::thread::local::LocalKey<T>::with
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/thread/local.rs:421:9
  57: tokio::coop::with_budget
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:95:5
  58: tokio::coop::budget
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:72:5
  59: tokio::runtime::thread_pool::worker::Context::run_task
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:430:9
  60: tokio::runtime::thread_pool::worker::Context::run
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:397:24
  61: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:382:17
  62: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/macros/scoped_tls.rs:61:9
  63: tokio::runtime::thread_pool::worker::run
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:379:5
  64: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/worker.rs:358:45
  65: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/task.rs:42:21
  66: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:165:17
  67: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/loom/std/unsafe_cell.rs:14:9
  68: tokio::runtime::task::core::CoreStage<T>::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/core.rs:155:13
  69: tokio::runtime::task::harness::poll_future::{{closure}}
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:470:19
  70: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/panic/unwind_safe.rs:271:9
  71: std::panicking::try::do_call
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panicking.rs:492:40
  72: __rust_try
  73: std::panicking::try
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panicking.rs:456:19
  74: std::panic::catch_unwind
             at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panic.rs:137:14
  75: tokio::runtime::task::harness::poll_future
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:458:18
  76: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:104:27
  77: tokio::runtime::task::harness::Harness<T,S>::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/harness.rs:57:15
  78: tokio::runtime::task::raw::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:144:5
  79: tokio::runtime::task::raw::RawTask::poll
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/raw.rs:84:18
  80: tokio::runtime::task::UnownedTask<S>::run
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/task/mod.rs:413:9
  81: tokio::runtime::blocking::pool::Task::run
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:91:9
  82: tokio::runtime::blocking::pool::Inner::run
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:325:17
  83: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/blocking/pool.rs:300:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Fri May 13 03:24:36 UTC 2022 [risedev]: Program exited with 134
```

**To Reproduce**
First observed at https://github.com/singularity-data/risingwave/runs/6416945963?check_suite_focus=true
Another one: https://github.com/singularity-data/risingwave/runs/6418831748?check_suite_focus=true#step:26:299

**Expected behavior**
No panic

**Additional context**
@likg227

**Comment by liurenjie1024** [comment]
I will take a look at this.

**Comment by likg227** [comment]
TPCH Q15 and Q22 are blocking by this issue.

**Comment by xiangjinwu** [comment]
Seems not fixed yet:
https://buildkite.com/singularity-data/pull-request/builds/903#01814691-01f2-4ee1-9acc-6f032a0d27fc
