### ISSUE TITLE
broken pipe error when running parallel sqllogictest

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#3051]
```
./risedev ci-start ci-3cn-1fe
./risedev slt -p 4566 './e2e_test/streaming/*.slt' -d dev -j 2
```

Will find a lot of broken pipe error, but I have no idea what's the cause.

**Comment by skyzh** [comment]
The playground works fine:

```
./risedev d
./risedev slt -p 4566 './e2e_test/streaming/*.slt' -d dev -j 8
```

**Comment by skyzh** [comment]
```
2022-06-08T04:00:19.533834Z ERROR risingwave_stream::executor::merge: RemoteInput tonic error status:status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }    
thread 'tokio-runtime-worker' panicked at 'upstream channel closed unexpectedly, please check error in upstream executors', src/stream/src/executor/merge.rs:193:40
stack backtrace:
2022-06-08T04:00:19.533781Z DEBUG tonic::codec::decode: decoder inner stream error: Status { code: Unknown, message: "error reading a body from connection: broken pipe", source: Some(hyper::Error(Body, Error { kind: Io(Kind(BrokenPipe)) })) }
2022-06-08T04:00:19.534117Z ERROR risingwave_stream::executor::merge: RemoteInput tonic error status:status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }    
2022-06-08T04:00:19.534143Z DEBUG tonic::codec::decode: decoder inner stream error: Status { code: Unknown, message: "error reading a body from connection: broken pipe", source: Some(hyper::Error(Body, Error { kind: Io(Kind(BrokenPipe)) })) }
2022-06-08T04:00:19.534163Z ERROR risingwave_stream::executor::merge: RemoteInput tonic error status:status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }    
thread 'tokio-runtime-worker' panicked at 'upstream channel closed unexpectedly, please check error in upstream executors', src/stream/src/executor/merge.rs:193:40
2022-06-08T04:00:19.534194Z DEBUG tonic::codec::decode: decoder inner stream error: Status { code: Unknown, message: "error reading a body from connection: broken pipe", source: Some(hyper::Error(Body, Error { kind: Io(Kind(BrokenPipe)) })) }
2022-06-08T04:00:19.534218Z ERROR risingwave_stream::executor::merge: RemoteInput tonic error status:status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }    
thread 'tokio-runtime-worker' panicked at 'upstream channel closed unexpectedly, please check error in upstream executors', src/stream/src/executor/merge.rs:193:40
2022-06-08T04:00:19.534246Z DEBUG tonic::codec::decode: decoder inner stream error: Status { code: Unknown, message: "error reading a body from connection: broken pipe", source: Some(hyper::Error(Body, Error { kind: Io(Kind(BrokenPipe)) })) }
thread 'tokio-runtime-worker' panicked at 'upstream channel closed unexpectedly, please check error in upstream executors', src/stream/src/executor/merge.rs:193:40
2022-06-08T04:00:19.534267Z ERROR risingwave_stream::executor::merge: RemoteInput tonic error status:status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }    
thread 'tokio-runtime-worker' panicked at 'upstream channel closed unexpectedly, please check error in upstream executors', src/stream/src/executor/merge.rs:193:40
2022-06-08T04:00:19.534321Z DEBUG tonic::codec::decode: decoder inner stream error: Status { code: Unknown, message: "error reading a body from connection: broken pipe", source: Some(hyper::Error(Body, Error { kind: Io(Kind(BrokenPipe)) })) }
2022-06-08T04:00:19.534336Z ERROR risingwave_stream::executor::merge: RemoteInput tonic error status:status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }    
thread 'tokio-runtime-worker' panicked at 'upstream channel closed unexpectedly, please check error in upstream executors', src/stream/src/executor/merge.rs:193:40
2022-06-08T04:00:19.534444Z DEBUG tonic::codec::decode: decoder inner stream error: Status { code: Unknown, message: "error reading a body from connection: broken pipe", source: Some(hyper::Error(Body, Error { kind: Io(Kind(BrokenPipe)) })) }
2022-06-08T04:00:19.534466Z ERROR risingwave_stream::executor::merge: RemoteInput tonic error status:status: Unknown, message: "error reading a body from connection: broken pipe", details: [], metadata: MetadataMap { headers: {} }    
thread 'tokio-runtime-worker' panicked at 'upstream channel closed unexpectedly, please check error in upstream executors', src/stream/src/executor/merge.rs:193:40
```

**Comment by skyzh** [comment]
Can be reproduced with:

Create 4 identical files:

```
statement ok
create table t1(v1 int);

statement ok
create table t2(v1 int);

statement ok
create table t3(v1 int);

statement ok
create table t4(v1 int);

statement ok
drop table t1;

statement ok
drop table t2;

statement ok
drop table t3;

statement ok
drop table t4;
```

named `_1.slt`, `_2.slt`, `_3.slt`, `_4.slt`, and run them in parallel.
