### ISSUE TITLE
streaming: append-only TopN panic

### ISSUE THREAD

**Issue by StrikeW** [singularity-data/risingwave#3286]
**Describe the bug**
Append-only TopN panic in inserting `managed_lower_state`.

```
thread 'tokio-runtime-worker' panicked at 'itertools: .zip_eq() reached end of one iterator before the other', /Users/siyuan/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.3/src/zip_eq_impl.rs:48:13
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/7466d5492b2d28d2ba5114dbe71511a6502ac822/library/std/src/panicking.rs:616:12
   1: <itertools::zip_eq_impl::ZipEq<I,J> as core::iter::traits::iterator::Iterator>::next
             at /Users/siyuan/.cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.3/src/zip_eq_impl.rs:48:13
   2: risingwave_common::util::ordered::serde::OrderedRowSerializer::serialize_datums
             at ./src/common/src/util/ordered/serde.rs:97:36
   3: risingwave_common::util::ordered::serde::OrderedRowSerializer::serialize
             at ./src/common/src/util/ordered/serde.rs:85:9
   4: risingwave_common::util::ordered::serde::serialize_pk
             at ./src/common/src/util/ordered/serde.rs:228:5
   5: risingwave_storage::table::state_table::StateTable<S>::insert
             at ./src/storage/src/table/state_table.rs:104:24
   6: risingwave_stream::executor::managed_state::top_n::top_n_state::ManagedTopNState<S,_>::insert::{{closure}}
             at ./src/stream/src/executor/managed_state/top_n/top_n_state.rs:196:26
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7466d5492b2d28d2ba5114dbe71511a6502ac822/library/core/src/future/mod.rs:91:19
   8: <risingwave_stream::executor::top_n_appendonly::InnerAppendOnlyTopNExecutor<S> as risingwave_stream::executor::top_n_executor::TopNExecutorBase>::apply_chunk::{{closure}}
             at ./src/stream/src/executor/top_n_appendonly.rs:201:56
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
```

**To Reproduce**

```
create table t4 (v1 real not null, v2 int not null, v3 real not null) with ('appendonly' = true);
create materialized view mv5 as select v1, v3 from t4 order by v1 limit 3 offset 3;
insert into t4 values (1,1,4), (5,1,4), (1,9,1), (9,8,1), (0,2,3);
```

**Expected behavior**
Populate the mview and doesn't panic

**Additional context**

**Comment by skyzh** [comment]
maybe schema mismatch or pk mismatch?

**Comment by StrikeW** [comment]
I am investigating

**Comment by StrikeW** [comment]
Any idea?  @wcy-fdu

**Comment by wcy-fdu** [comment]
Let me take a look

**Comment by wcy-fdu** [comment]
I will send a PR to fix this bug.
