### ISSUE TITLE
streaming: double insert when parallel level is high

### ISSUE THREAD

**Issue by skyzh** [singularity-data/risingwave#3308]
```
compute-node-0  | thread 'tokio-runtime-worker' panicked at 'invalid flush status: double insert [1, 128, 0, 0, 0, 1, 49, 45, 39, 1, 130, 57, 132, 85, 171, 0, 16, 26] -> Row([Some(Int64(20000039)), Some(Utf8("AIR")), Some(Int64(160304765224357914)), Some(Int64(0))])', src/storage/src/table/mem_table.rs:75:21
compute-node-0  | stack backtrace:
compute-node-0  | thread 'tokio-runtime-worker' panicked at 'invalid flush status: double insert [1, 128, 0, 0, 0, 1, 49, 45, 96, 1, 130, 57, 132, 85, 171, 0, 16, 67] -> Row([Some(Int64(20000096)), Some(Utf8("TRUCK")), Some(Int64(160304765224357955)), Some(Int64(0))])', src/storage/src/table/mem_table.rs:75:21
compute-node-0  | thread 'tokio-runtime-worker' panicked at 'invalid flush status: double insert [1, 128, 0, 0, 0, 1, 49, 45, 130, 1, 130, 57, 132, 85, 171, 0, 16, 108] -> Row([Some(Int64(20000130)), Some(Utf8("RAIL")), Some(Int64(160304765224357996)), Some(Int64(0))])', src/storage/src/table/mem_table.rs:75:21
```

```
diff --git a/src/meta/src/rpc/service/ddl_service.rs b/src/meta/src/rpc/service/ddl_service.rs
index 99b251571..735b3a0a1 100644
--- a/src/meta/src/rpc/service/ddl_service.rs
+++ b/src/meta/src/rpc/service/ddl_service.rs
@@ -418,7 +418,7 @@ where
         );

         // Resolve fragments.
-        let parallel_degree = self
+        let parallel_degree = 8 * self
             .cluster_manager
             .get_parallel_unit_count(Some(ParallelUnitType::Hash))
             .await;
```

**Comment by jon-chuang** [comment]
What query is this?

**Comment by skyzh** [comment]
Q12. By the way I'm changing parallel degree in a wrong way. If I change `DEFAULT_WORK_NODE_PARALLEL_DEGREE`, then everything goes fine. So I guess there's some problem with meta, which will block the implementation of scaling.

**Comment by jon-chuang** [comment]
I think some sort of buggy behaviour is expected, right? The node itself does not have the available `ParallelUnit`s, but the meta service tries to map to those `ParallelUnit`s here: https://github.com/singularity-data/risingwave/blob/35bb16a3b236ba1f56a2bf3ed05d14d650cfa4e4/src/meta/src/stream/stream_manager.rs#L378

**Comment by skyzh** [comment]
That's cool. So we should adjust parallel unit in some specific ways.

**Comment by jon-chuang** [comment]
Well, basically, the constraint we have I think is that number of actors in a fragment must be `<= parallel_units` in the cluster.

That's because the vnode count is = parallel_unit count
