### ISSUE TITLE
streaming: panic on creating mv on table with struct type

### ISSUE THREAD

**Issue by StrikeW** [singularity-data/risingwave#3335]
**Describe the bug**
compute node panics on creating mv on table with struct type

stack trace on CN:
```
2022-06-20T08:05:00.766602Z DEBUG risingwave_batch::task::task_execution: data chunk stream shuts down
thread 'tokio-runtime-worker' panicked at 'actor failed: Stream error: Storage error: Array error: Invalid datum type
  backtrace of `StreamExecutorError`:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/7466d5492b2d28d2ba5114dbe71511a6502ac822/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/7466d5492b2d28d2ba5114dbe71511a6502ac822/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/7466d5492b2d28d2ba5114dbe71511a6502ac822/library/std/src/backtrace.rs:328:13
   3: <risingwave_stream::executor::error::StreamExecutorError as core::convert::From<risingwave_stream::executor::error::StreamExecutorErrorInner>>::from
             at ./src/stream/src/executor/error.rs:102:10
   4: <T as core::convert::Into<U>>::into
             at /rustc/7466d5492b2d28d2ba5114dbe71511a6502ac822/library/core/src/convert/mod.rs:550:9
   5: risingwave_stream::executor::error::StreamExecutorError::storage
             at ./src/stream/src/executor/error.rs:66:9
   6: <risingwave_stream::executor::error::StreamExecutorError as core::convert::From<risingwave_storage::error::StorageError>>::from
             at ./src/stream/src/executor/error.rs:132:9
   7: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/7466d5492b2d28d2ba5114dbe71511a6502ac822/library/core/src/result.rs:2125:27
   8: risingwave_stream::executor::batch_query::BatchQueryExecutor<S>::execute_inner::{{closure}}
             at ./src/stream/src/executor/batch_query.rs:84:14
   9: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/siyuan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  10: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/siyuan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:120:9
  11: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/siyuan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:120:9
  12: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/siyuan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/mod.rs:1626:9
  13: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/siyuan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/next.rs:32:9
  14: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
             at /Users/siyuan/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-futures-0.2.5/src/lib.rs:283:9
  15: risingwave_stream::executor::debug::trace::trace::{{closure}}
             at ./src/stream/src/executor/debug/trace.rs:52:63
  16: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/siyuan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  17: risingwave_stream::executor::debug::schema_check::schema_check::{{closure}}
             at ./src/stream/src/executor/debug/schema_check.rs:27:1
  18: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/siyuan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  19: risingwave_stream::executor::debug::epoch_check::epoch_check::{{closure}}
             at ./src/stream/src/executor/debug/epoch_check.rs:24:1
  20: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/siyuan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  21: risingwave_stream::executor::debug::update_check::update_check::{{closure}}
             at ./src/stream/src/executor/debug/update_check.rs:27:1
  22: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/siyuan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  23: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/siyuan/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:120:9
   ...
```

**To Reproduce**
```
create table st (v1 int, v2 struct<v1 int, v2 struct<v1 int, v2 int>>);
insert into st values(1,(1,(1,2)));
insert into st values(2,(2,(2,3)));
create materialized view mv1 as select v1, v2 from st;
```

**Expected behavior**
Create and populate MV successfully

**Additional context**

**Comment by StrikeW** [comment]
cc @neverchanje

**Comment by StrikeW** [comment]
Have been fixed
