### ISSUE TITLE
Internal Error: correlated InputRef having some issue when group by table outside the subquery/

### ISSUE THREAD

**Issue by marvenlee2486** [singularity-data/risingwave#3934]
**Describe the bug**
The bug
![image](https://user-images.githubusercontent.com/65748142/179340944-e08439e4-6dcb-456a-81b2-f6ea646ec548.png)

The expected from pg
![image](https://user-images.githubusercontent.com/65748142/179340959-14c1389e-e0de-4da9-9b53-d608e37d99f4.png)

The frontend log
```
2022-07-16T05:14:10.021726Z ERROR pgwire::pg_protocol: Error: ReadMsgError: unexpected end of file.
2022-07-16T05:16:14.821982Z ERROR risingwave_frontend::optimizer::plan_node::logical_join: LeftSemi    
2022-07-16T05:16:14.822212Z ERROR risingwave_frontend::optimizer::plan_node::logical_join: Inner    
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code: CorrelatedInputRef CorrelatedInputRef { index: 1, depth: 1 } has not been decorrelated', src/frontend/src/expr/correlated_input_ref.rs:63:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/bb8c2f41174caceec00c28bc6c5c20ae9f9a175c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/bb8c2f41174caceec00c28bc6c5c20ae9f9a175c/library/core/src/panicking.rs:142:14
   2: <risingwave_frontend::expr::correlated_input_ref::CorrelatedInputRef as risingwave_frontend::expr::Expr>::to_expr_proto
             at ./src/frontend/src/expr/correlated_input_ref.rs:63:9
   3: <risingwave_frontend::expr::ExprImpl as risingwave_frontend::expr::Expr>::to_expr_proto
             at ./src/frontend/src/expr/mod.rs:416:48
```

**To Reproduce**
```
create table t1 (x int, y int);
create table t2 (x int, y int);
select * from t1 where x in (select t1.x from t2 group by t1.x);
```

**Expected behavior**

**Additional context**

**Comment by jon-chuang** [comment]
As discussed with @likg227 previously, we should throw an error, not panic

**Comment by jon-chuang** [comment]
Could you show the logical plan?

**Comment by jon-chuang** [comment]
Btw, why do you think this query gives 0 rows on postgres?

```sql
create table t1  (x int, y int);
create table t2  (x int, y int);
insert into t1 values (1, 1);
insert into t1 values (1, 2);
insert into t2 values (1, 1);
insert into t2 values (1, 2);
select *  from t1 where x in (select sum(t2.x) from t2 group by t1.y);
```

**Comment by marvenlee2486** [comment]
Oops, I am sorry, i miss your comment here.

It seems like this issue is being resolved by returning the same output as postgre.

sum(t2.x) return 2 (it shown in next comment),

I think this means t1 and t2 is not join at all or affected at all?

**Comment by marvenlee2486** [comment]
Anyway our system.

```
dev=> select *  from t1 where y = (select sum(t2.x) from t2 group by t1.y);
 x | y 
---+---
 1 | 2
(1 row)

dev=> select *  from t1 where y in (select sum(t2.x) from t2 group by t1.y);
 x | y 
---+---
(0 rows)

```

Postgresql

```
postgres=# select *  from t1 where y in (select sum(t2.x) from t2 group by t1.y);
 x | y
---+---
 1 | 2
(1 row)


postgres=# select *  from t1 where y = (select sum(t2.x) from t2 group by t1.y);
 x | y
---+---
 1 | 2
(1 row)
```

is this some error with in?

**Comment by xiangjinwu** [comment]
possibly related: #4203

**Comment by xiangjinwu** [comment]
> is this some error with in?

I found the issue. This modified query works as expected:
```
dev=> select *  from t1 where y in (select sum(t2.x)::int from t2 group by t1.y);
 x | y 
---+---
 1 | 2
(1 row)
```

Note that result of `sum` is casted from int64 to int32.

Regarding `=` vs `in`, the former generates an inner join with output indices only referencing the left side, while the latter generates a semi join.

This means batch hash semi join is not handling equality of different types correctly. @likg227 has started working on #3478, which is expected to eliminate the need of an explicit cast.
