### ISSUE TITLE
logical_agg.rs:323:68 panic! at index out of bounds 

### ISSUE THREAD

**Issue by marvenlee2486** [singularity-data/risingwave#3989]
> ![image](https://user-images.githubusercontent.com/65748142/179574911-9f1d5861-525a-426a-b0ec-ffcd063dcef7.png)
> 
> This is not always will be triggered, But suspected it is an error in implementation on the agg logical between the time I done this and the time i merge the branch as this error occur after I merge the branch.

In order to debug properly, I put some println! under `tests\sqlsmith\tests\test_runner.rs`
and I debug out it is 
Line 60 that throw the error. 
Because some I print the statement on Line 59, and it panic, so it won,t print line 61, 
Therefore It surely line 60 panic.

As it not everytimes will have this error, I keep some of the stmt that cause it to failed. I will attach in our slack channel

_Originally posted by @marvenlee2486 in https://github.com/singularity-data/risingwave/pull/3932#issuecomment-1188018207_

**Comment by marvenlee2486** [comment]
```
CreateView {
    or_replace: false,
    materialized: true,
    name: ObjectName(
        [
            Ident {
                value: "m6",
                quote_style: None,
            },
        ],
    ),
    columns: [],
    query: Query {
        with: None,
        body: Select(
            Select {
                distinct: false,
                projection: [
                    ExprWithAlias {
                        expr: BinaryOp {
                            left: Nested(
                                BinaryOp {
                                    left: Function(
                                        Function {
                                            name: ObjectName(
                                                [
                                                    Ident {
                                                        value: "max",
                                                        quote_style: None,
                                                    },
                                                ],
                                            ),
                                            args: [
                                                Unnamed(
                                                    Expr(
                                                        BinaryOp {
                                                            left: CompoundIdentifier(
                                                                [
                                                                    Ident {
                                                                        value: "t0",
                                                                        quote_style: None,
                                                                    },
                                                                    Ident {
                                                                        value: "col_0",
                                                                        quote_style: None,
                                                                    },
                                                                ],
                                                            ),
                                                            op: BitwiseAnd,
                                                            right: CompoundIdentifier(
                                                                [
                                                                    Ident {
                                                                        value: "t0",
                                                                        quote_style: None,
                                                                    },
                                                                    Ident {
                                                                        value: "col_0",
                                                                        quote_style: None,
                                                                    },
                                                                ],
                                                            ),
                                                        },
                                                    ),
                                                ),
                                            ],
                                            over: None,
                                            distinct: true,
                                            order_by: [],
                                            filter: None,
                                        },
                                    ),
                                    op: Divide,
                                    right: TypedString {
                                        data_type: SmallInt(
                                            None,
                                        ),
                                        value: "24",
                                    },
                                },
                            ),
                            op: PGBitwiseShiftRight,
                            right: TypedString {
                                data_type: SmallInt(
                                    None,
                                ),
                                value: "26",
                            },
                        },
                        alias: Ident {
                            value: "col_0",
                            quote_style: None,
                        },
                    },
                ],
                from: [
                    TableWithJoins {
                        relation: Table {
                            name: ObjectName(
                                [
                                    Ident {
                                        value: "m1",
                                        quote_style: None,
                                    },
                                ],
                            ),
                            alias: Some(
                                TableAlias {
                                    name: Ident {
                                        value: "t0",
                                        quote_style: None,
                                    },
                                    columns: [],
                                },
                            ),
                            args: [],
                        },
                        joins: [],
                    },
                ],
                lateral_views: [],
                selection: Some(
                    Value(
                        Boolean(
                            false,
                        ),
                    ),
                ),
                group_by: [
                    CompoundIdentifier(
                        [
                            Ident {
                                value: "t0",
                                quote_style: None,
                            },
                            Ident {
                                value: "col_0",
                                quote_style: None,
                            },
                        ],
                    ),
                ],
                having: None,
            },
        ),
        order_by: [],
        limit: None,
        offset: None,
        fetch: None,
    },
    with_options: [],
}
```

```
test run_sqlsmith_on_frontend_27 ... FAILED

failures:

failures:
    run_sqlsmith_on_frontend_27

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 31 filtered out; finished in 0.18s


--- TRY 1 STDERR:                         risingwave_sqlsmith::test_runner run_sqlsmith_on_frontend_27 ---
thread 'run_sqlsmith_on_frontend_27' panicked at 'index out of bounds: the len is 4 but the index is 8', src/frontend/src/optimizer/plan_node/logical_agg.rs:323:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by marvenlee2486** [comment]
```
CreateView {
    or_replace: false,
    materialized: true,
    name: ObjectName(
        [
            Ident {
                value: "m7",
                quote_style: None,
            },
        ],
    ),
    columns: [],
    query: Query {
        with: None,
        body: Select(
            Select {
                distinct: false,
                projection: [
                    ExprWithAlias {
                        expr: BinaryOp {
                            left: Value(
                                Number(
                                    "81.59011341770372",
                                    false,
                                ),
                            ),
                            op: Modulo,
                            right: TypedString {
                                data_type: Int(
                                    None,
                                ),
                                value: "67",
                            },
                        },
                        alias: Ident {
                            value: "col_0",
                            quote_style: None,
                        },
                    },
                    ExprWithAlias {
                        expr: Value(
                            Number(
                                "81.00195891452029",
                                false,
                            ),
                        ),
                        alias: Ident {
                            value: "col_1",
                            quote_style: None,
                        },
                    },
                    ExprWithAlias {
                        expr: Function(
                            Function {
                                name: ObjectName(
                                    [
                                        Ident {
                                            value: "min",
                                            quote_style: None,
                                        },
                                    ],
                                ),
                                args: [
                                    Unnamed(
                                        Expr(
                                            TypedString {
                                                data_type: Real,
                                                value: "36.763521126937974",
                                            },
                                        ),
                                    ),
                                ],
                                over: None,
                                distinct: true,
                                order_by: [],
                                filter: None,
                            },
                        ),
                        alias: Ident {
                            value: "col_2",
                            quote_style: None,
                        },
                    },
                ],
                from: [
                    TableWithJoins {
                        relation: Table {
                            name: ObjectName(
                                [
                                    Ident {
                                        value: "m1",
                                        quote_style: None,
                                    },
                                ],
                            ),
                            alias: Some(
                                TableAlias {
                                    name: Ident {
                                        value: "t0",
                                        quote_style: None,
                                    },
                                    columns: [],
                                },
                            ),
                            args: [],
                        },
                        joins: [],
                    },
                ],
                lateral_views: [],
                selection: None,
                group_by: [
                    CompoundIdentifier(
                        [
                            Ident {
                                value: "t0",
                                quote_style: None,
                            },
                            Ident {
                                value: "col_1",
                                quote_style: None,
                            },
                        ],
                    ),
                    CompoundIdentifier(
                        [
                            Ident {
                                value: "t0",
                                quote_style: None,
                            },
                            Ident {
                                value: "col_0",
                                quote_style: None,
                            },
                        ],
                    ),
                    CompoundIdentifier(
                        [
                            Ident {
                                value: "t0",
                                quote_style: None,
                            },
                            Ident {
                                value: "col_2",
                                quote_style: None,
                            },
                        ],
                    ),
                ],
                having: None,
            },
        ),
        order_by: [
            OrderByExpr {
                expr: CompoundIdentifier(
                    [
                        Ident {
                            value: "t0",
                            quote_style: None,
                        },
                        Ident {
                            value: "col_1",
                            quote_style: None,
                        },
                    ],
                ),
                asc: Some(
                    false,
                ),
                nulls_first: None,
            },
        ],
        limit: None,
        offset: None,
        fetch: None,
    },
    with_options: [],
}
test run_sqlsmith_on_frontend_9 ... FAILED

failures:

failures:
    run_sqlsmith_on_frontend_9

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 31 filtered out; finished in 0.16s
```
```
--- TRY 1 STDERR:                         risingwave_sqlsmith::test_runner run_sqlsmith_on_frontend_9 ---
thread 'run_sqlsmith_on_frontend_9' panicked at 'index out of bounds: the len is 6 but the index is 8', src/frontend/src/optimizer/plan_node/logical_agg.rs:323:68
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by st1page** [comment]
@likg227 Would you please take a look?

**Comment by skyzh** [comment]
This means that the sqlsmith test is not deterministic... It should produce exactly the same query every time we run it. 🤣

**Comment by st1page** [comment]
> This means that the sqlsmith test is not deterministic... It should produce exactly the same query every time we run it. rofl

I think it is ok because sqlsmith tests are not in CI? And after we find the error case we can fix them, then check if it deserves to be added to our e2e or planner test.

**Comment by likg227** [comment]
Becase selective aggregates for stream hasn't been implemented yet, stream distinct aggregates is not disallowed not. But we can solve the bug of frontend first.

**Comment by likg227** [comment]
@marvenlee2486  selective aggregates means inputs will be filtered first and then aggregated. So when I say selective aggregates, I mean `agg(..) filter(where ..)`.

**Comment by marvenlee2486** [comment]
https://github.com/singularity-data/risingwave/pull/4013
