### ISSUE TITLE
sqlsmith bug hunt: `LogicalTopN::prune_col` index out of bounds

### ISSUE THREAD

**Issue by kwannoel** [singularity-data/risingwave#4025]
Happens when I include `with table` in a cross join.

```sql
FROM with_table, <some_table>, ...
```

## To reproduce

1. Create tables with the following SQL scripts
- https://github.com/singularity-data/risingwave/blob/e6a9f798bd02212cb914715f9cca7129fa875853/src/tests/sqlsmith/tests/testdata/tpch.sql
- https://github.com/singularity-data/risingwave/blob/e6a9f798bd02212cb914715f9cca7129fa875853/src/tests/sqlsmith/tests/testdata/nexmark.sql

2. Run the following query
```sql
 WITH with_0 AS
(
         SELECT   31 * float '22.067747038288154'                               as col_0,
                  interval '629432'                                             AS col_1
         FROM     region                                                        AS t0,
                  orders                                                        AS t1,
                  part                                                          AS t2,
                  supplier                                                      AS t3,
                  nation                                                        AS t4,
                  hop(person, person.datetime, interval '1', interval '193590') AS hop_5
         GROUP BY t1.o_custkey
         HAVING   true
         ORDER BY t1.o_custkey DESC,
                  t1.o_custkey DESC,
                  t1.o_custkey DESC limit 80)
SELECT   real '11.120695510363454' AS col_0,
         t0.l_orderkey             AS col_1,
         int '40'                  AS col_2
FROM     with_0,
         lineitem                                           AS t0,
         supplier                                           AS t1,
         partsupp                                           AS t2,
         tumble(person, person.datetime, interval '527741') AS tumble_3,
         orders                                             AS t4
GROUP BY t1.s_address,
         t0.l_discount,
         t0.l_orderkey,
         t0.l_extendedprice,
         tumble_3.emailaddress,
         t4.o_shippriority,
         t0.l_shipinstruct,
         t2.ps_suppkey,
         t1.s_phone,
         tumble_3.creditcard,
         t4.o_custkey,
         t4.o_orderpriority,
         t0.l_quantity,
         t1.s_nationkey,
         t0.l_returnflag,
         tumble_3.city,
         t2.ps_comment,
         tumble_3.NAME,
         t0.l_receiptdate,
         t2.ps_availqty,
         t0.l_partkey; 
```

Error trace:
```
2022-07-19T11:03:07.732986Z  INFO risingwave_frontend::scheduler::hummock_snapshot_manager: Unpin epoch 2686542633828352 with RPC
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 3 but the index is 3', src/frontend/src/utils/column_index_mapping.rs:148:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_bounds_check
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/core/src/panicking.rs:84:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index_mut
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/core/src/slice/index.rs:248:14
   4: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/alloc/src/vec/mod.rs:2639:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/alloc/src/vec/mod.rs:2639:9
   6: risingwave_frontend::utils::column_index_mapping::ColIndexMapping::with_remaining_columns
             at ./src/frontend/src/utils/column_index_mapping.rs:148:13
   7: <risingwave_frontend::optimizer::plan_node::logical_topn::LogicalTopN as risingwave_frontend::optimizer::plan_node::col_pruning::ColPrunable>::prune_col
             at ./src/frontend/src/optimizer/plan_node/logical_topn.rs:183:17
   8: <risingwave_frontend::optimizer::plan_node::logical_join::LogicalJoin as risingwave_frontend::optimizer::plan_node::col_pruning::ColPrunable>::prune_col
             at ./src/frontend/src/optimizer/plan_node/logical_join.rs:639:13
   9: <risingwave_frontend::optimizer::plan_node::logical_join::LogicalJoin as risingwave_frontend::optimizer::plan_node::col_pruning::ColPrunable>::prune_col
             at ./src/frontend/src/optimizer/plan_node/logical_join.rs:639:13
  10: <risingwave_frontend::optimizer::plan_node::logical_project::LogicalProject as risingwave_frontend::optimizer::plan_node::col_pruning::ColPrunable>::prune_col
             at ./src/frontend/src/optimizer/plan_node/logical_project.rs:304:25
  11: <risingwave_frontend::optimizer::plan_node::logical_join::LogicalJoin as risingwave_frontend::optimizer::plan_node::col_pruning::ColPrunable>::prune_col
             at ./src/frontend/src/optimizer/plan_node/logical_join.rs:639:13
  12: <risingwave_frontend::optimizer::plan_node::logical_join::LogicalJoin as risingwave_frontend::optimizer::plan_node::col_pruning::ColPrunable>::prune_col
             at ./src/frontend/src/optimizer/plan_node/logical_join.rs:639:13
  13: <risingwave_frontend::optimizer::plan_node::logical_project::LogicalProject as risingwave_frontend::optimizer::plan_node::col_pruning::ColPrunable>::prune_col
             at ./src/frontend/src/optimizer/plan_node/logical_project.rs:304:25
  14: <risingwave_frontend::optimizer::plan_node::logical_join::LogicalJoin as risingwave_frontend::optimizer::plan_node::col_pruning::ColPrunable>::prune_col
             at ./src/frontend/src/optimizer/plan_node/logical_join.rs:639:13
  15: <risingwave_frontend::optimizer::plan_node::logical_project::LogicalProject as risingwave_frontend::optimizer::plan_node::col_pruning::ColPrunable>::prune_col
             at ./src/frontend/src/optimizer/plan_node/logical_project.rs:304:25
  16: <risingwave_frontend::optimizer::plan_node::logical_agg::LogicalAgg as risingwave_frontend::optimizer::plan_node::col_pruning::ColPrunable>::prune_col
             at ./src/frontend/src/optimizer/plan_node/logical_agg.rs:887:25
  17: <risingwave_frontend::optimizer::plan_node::logical_project::LogicalProject as risingwave_frontend::optimizer::plan_node::col_pruning::ColPrunable>::prune_col
             at ./src/frontend/src/optimizer/plan_node/logical_project.rs:304:25
  18: risingwave_frontend::optimizer::PlanRoot::gen_optimized_logical_plan
             at ./src/frontend/src/optimizer/mod.rs:223:16
  19: risingwave_frontend::optimizer::PlanRoot::gen_batch_query_plan
             at ./src/frontend/src/optimizer/mod.rs:247:24
  20: risingwave_frontend::handler::query::distribute_execute::{{closure}}
             at ./src/frontend/src/handler/query.rs:93:20
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/core/src/future/mod.rs:91:19
  22: risingwave_frontend::handler::query::handle_query::{{closure}}
             at ./src/frontend/src/handler/query.rs:51:69
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/core/src/future/mod.rs:91:19
  24: risingwave_frontend::handler::handle::{{closure}}
             at ./src/frontend/src/handler/mod.rs:117:66
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/core/src/future/mod.rs:91:19
  26: <risingwave_frontend::session::SessionImpl as pgwire::pg_server::Session>::run_statement::{{closure}}
             at ./src/frontend/src/session.rs:560:42
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/core/src/future/mod.rs:91:19
  28: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/core/src/future/future.rs:124:9
  29: pgwire::pg_protocol::PgProtocol<S,SM>::process_query_msg::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:325:32
  30: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/core/src/future/mod.rs:91:19
  31: pgwire::pg_protocol::PgProtocol<S,SM>::do_process_inner::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:193:60
  32: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/core/src/future/mod.rs:91:19
  33: pgwire::pg_protocol::PgProtocol<S,SM>::do_process::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:122:14
  34: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/core/src/future/mod.rs:91:19
  35: pgwire::pg_protocol::PgProtocol<S,SM>::process::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:100:14
  36: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/core/src/future/mod.rs:91:19
  37: pgwire::pg_server::pg_serve_conn::{{closure}}
             at ./src/utils/pgwire/src/pg_server.rs:112:14
  38: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/core/src/future/mod.rs:91:19
  39: pgwire::pg_server::pg_serve::{{closure}}::{{closure}}
             at ./src/utils/pgwire/src/pg_server.rs:85:55
  40: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/core/src/future/mod.rs:91:19
  41: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.34/src/instrument.rs:272:9
  42: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:165:17
  43: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/loom/std/unsafe_cell.rs:14:9
  44: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:155:13
  45: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:470:19
  46: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/core/src/panic/unwind_safe.rs:271:9
  47: std::panicking::try::do_call
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/std/src/panicking.rs:492:40
  48: __rust_try
  49: std::panicking::try
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/std/src/panicking.rs:456:19
  50: std::panic::catch_unwind
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/std/src/panic.rs:137:14
  51: tokio::runtime::task::harness::poll_future
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:458:18
  52: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:104:27
  53: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:57:15
  54: tokio::runtime::task::raw::poll
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:144:5
  55: tokio::runtime::task::raw::RawTask::poll
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:84:18
  56: tokio::runtime::task::LocalNotified<S>::run
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/mod.rs:376:9
  57: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:435:13
  58: tokio::coop::with_budget::{{closure}}
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:102:9
  59: std::thread::local::LocalKey<T>::try_with
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/std/src/thread/local.rs:445:16
  60: std::thread::local::LocalKey<T>::with
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/std/src/thread/local.rs:421:9
  61: tokio::coop::with_budget
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:95:5
  62: tokio::coop::budget
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/coop.rs:72:5
  63: tokio::runtime::thread_pool::worker::Context::run_task
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:434:9
  64: tokio::runtime::thread_pool::worker::Context::run
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:401:24
  65: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:386:17
  66: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/macros/scoped_tls.rs:61:9
  67: tokio::runtime::thread_pool::worker::run
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:383:5
  68: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/thread_pool/worker.rs:362:45
  69: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/task.rs:42:21
  70: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.34/src/instrument.rs:272:9
  71: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:165:17
  72: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/loom/std/unsafe_cell.rs:14:9
  73: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/core.rs:155:13
  74: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:470:19
  75: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/core/src/panic/unwind_safe.rs:271:9
  76: std::panicking::try::do_call
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/std/src/panicking.rs:492:40
  77: __rust_try
  78: std::panicking::try
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/std/src/panicking.rs:456:19
  79: std::panic::catch_unwind
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/std/src/panic.rs:137:14
  80: tokio::runtime::task::harness::poll_future
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:458:18
  81: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:104:27
  82: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/harness.rs:57:15
  83: tokio::runtime::task::raw::poll
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:144:5
  84: tokio::runtime::task::raw::RawTask::poll
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/raw.rs:84:18
  85: tokio::runtime::task::UnownedTask<S>::run
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/task/mod.rs:413:9
  86: tokio::runtime::blocking::pool::Task::run
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs:91:9
  87: tokio::runtime::blocking::pool::Inner::run
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs:325:17
  88: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/noel/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.2/src/runtime/blocking/pool.rs:300:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Tue Jul 19 11:03:23 UTC 2022 [risedev]: Program exited with 134
```

**Comment by xiangjinwu** [comment]
A shorter query to reproduce the indexing issue in `LogicalTopN::prune_col`:
```
create table t (v1 int, v2 int, v3 int);
explain select v3 from (select * from t order by v3, v2 limit 2) as s;
```
```
2022-07-20T05:48:42.017753Z DEBUG risingwave_compute::rpc::service::stream_service: create table source id=1003
thread 'tokio-runtime-worker' panicked at 'index out of bounds: the len is 2 but the index is 2', src/frontend/src/utils/column_index_mapping.rs:148:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_bounds_check
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/core/src/panicking.rs:84:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index_mut
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/core/src/slice/index.rs:248:14
   4: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/alloc/src/vec/mod.rs:2639:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::IndexMut<I>>::index_mut
             at /rustc/263edd43c5255084292329423c61a9d69715ebfa/library/alloc/src/vec/mod.rs:2639:9
   6: risingwave_frontend::utils::column_index_mapping::ColIndexMapping::with_remaining_columns
             at ./src/frontend/src/utils/column_index_mapping.rs:148:13
   7: <risingwave_frontend::optimizer::plan_node::logical_topn::LogicalTopN as risingwave_frontend::optimizer::plan_node::col_pruning::ColPrunable>::prune_col
             at ./src/frontend/src/optimizer/plan_node/logical_topn.rs:184:17
   8: <risingwave_frontend::optimizer::plan_node::logical_project::LogicalProject as risingwave_frontend::optimizer::plan_node::col_pruning::ColPrunable>::prune_col
             at ./src/frontend/src/optimizer/plan_node/logical_project.rs:304:25
   9: risingwave_frontend::optimizer::PlanRoot::gen_optimized_logical_plan
             at ./src/frontend/src/optimizer/mod.rs:223:16
  10: risingwave_frontend::optimizer::PlanRoot::gen_batch_query_plan
             at ./src/frontend/src/optimizer/mod.rs:247:24
  11: risingwave_frontend::handler::explain::handle_explain
             at ./src/frontend/src/handler/explain.rs:93:13
```
