### ISSUE TITLE
bug: actor panicked at `get_compaction_group_id` timeout with nexmark q7

### ISSUE THREAD

**Issue by BugenZhao** [singularity-data/risingwave#4427]
When running nexmark q7 with a huge number of parallelism (30*3) and very high source throughput under release profile, we find that `get_compaction_group_id` timeout.

Since the executors are not able to handle this error, the actor simply panics.

```
thread 'tokio-runtime-worker' panicked at 'actor failed: Stream error: Storage error: Hummock error: Other error get_compaction_group_id 1003 timeout.
  backtrace of inner error:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/backtrace.rs:328:13
   3: <risingwave_storage::hummock::error::HummockError as core::convert::From<risingwave_storage::hummock::error::HummockErrorInner>>::from
             at ./src/storage/src/hummock/error.rs:55:10
   4: <T as core::convert::Into<U>>::into
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/convert/mod.rs:550:9
   5: risingwave_storage::hummock::error::HummockError::other
             at ./src/storage/src/hummock/error.rs:117:9
   6: risingwave_storage::hummock::HummockStorage::get_compaction_group_id::{{closure}}
             at ./src/storage/src/hummock/mod.rs:216:27
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   8: risingwave_storage::hummock::state_store::<impl risingwave_storage::hummock::HummockStorage>::get::{{closure}}
             at ./src/storage/src/hummock/state_store.rs:228:75
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  10: risingwave_storage::hummock::state_store::<impl risingwave_storage::store::StateStore for risingwave_storage::hummock::HummockStorage>::get::{{closure}}
             at ./src/storage/src/hummock/state_store.rs:351:49
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  12: <risingwave_common::util::debug::trace_context::StackTraced<F> as core::future::future::Future>::poll
             at ./src/common/src/util/debug/trace_context.rs:321:23
  13: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/future/fuse.rs:86:37
  14: <risingwave_storage::monitor::monitored_store::MonitoredStateStore<S> as risingwave_storage::store::StateStore>::get::{{closure}}
             at ./src/storage/src/monitor/monitored_store.rs:101:42
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  16: risingwave_storage::keyspace::Keyspace<S>::get::{{closure}}
             at ./src/storage/src/keyspace.rs:100:62
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  18: risingwave_stream::executor::source::state::SourceStateHandler<S>::restore_states::{{closure}}
             at ./src/stream/src/executor/source/state.rs:106:14
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  20: risingwave_stream::executor::source::state::SourceStateHandler<S>::try_recover_from_state_store::{{closure}}
             at ./src/stream/src/executor/source/state.rs:117:69
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  22: risingwave_stream::executor::source::source_executor::SourceExecutor<S>::into_stream::{{closure}}
             at ./src/stream/src/executor/source/source_executor.rs:216:18
  23: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  24: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:120:9
  25: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:120:9
  26: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/mod.rs:1626:9
  27: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/next.rs:32:9
  28: risingwave_stream::executor::debug::trace::metrics::{{closure}}
             at ./src/stream/src/executor/debug/trace.rs:98:44
  29: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  30: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:120:9
  31: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/mod.rs:1626:9
  32: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/next.rs:32:9
  33: <risingwave_common::util::debug::trace_context::StackTraced<F> as core::future::future::Future>::poll
             at ./src/common/src/util/debug/trace_context.rs:321:23
  34: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/future/fuse.rs:86:37
  35: risingwave_stream::executor::debug::trace::stack_trace::{{closure}}
             at ./src/stream/src/executor/debug/trace.rs:132:10
  36: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  37: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:120:9
  38: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/mod.rs:1626:9
  39: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/next.rs:32:9
  40: risingwave_stream::executor::debug::epoch_check::epoch_check::{{closure}}
             at ./src/stream/src/executor/debug/epoch_check.rs:31:44
  41: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  42: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:120:9
  43: risingwave_stream::executor::simple::SimpleExecutorWrapper<E>::execute_inner::{{closure}}
             at ./src/stream/src/executor/simple.rs:69:5
  44: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  45: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:120:9
  46: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:120:9
  47: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/mod.rs:1626:9
  48: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/next.rs:32:9
  49: risingwave_stream::executor::debug::trace::metrics::{{closure}}
             at ./src/stream/src/executor/debug/trace.rs:98:44
  50: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  51: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:120:9
  52: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/mod.rs:1626:9
  53: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/next.rs:32:9
  54: <risingwave_common::util::debug::trace_context::StackTraced<F> as core::future::future::Future>::poll
             at ./src/common/src/util/debug/trace_context.rs:321:23
  55: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/future/fuse.rs:86:37
  56: risingwave_stream::executor::debug::trace::stack_trace::{{closure}}
             at ./src/stream/src/executor/debug/trace.rs:132:10
  57: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  58: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:120:9
  59: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/mod.rs:1626:9
  60: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/next.rs:32:9
  61: risingwave_stream::executor::debug::epoch_check::epoch_check::{{closure}}
             at ./src/stream/src/executor/debug/epoch_check.rs:31:44
  62: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  63: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:120:9
  64: <risingwave_stream::executor::dispatch::DispatchExecutor as risingwave_stream::executor::StreamConsumer>::execute::{{closure}}
             at ./src/stream/src/executor/dispatch.rs:256:9
  65: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  66: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:120:9
  67: <&mut S as futures_core::stream::Stream>::poll_next
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:104:9
  68: <tokio_stream::stream_ext::next::Next<St> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-stream-0.1.9/src/stream_ext/next.rs:42:9
  69: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-futures-0.2.5/src/lib.rs:283:9
  70: <risingwave_common::util::debug::trace_context::StackTraced<F> as core::future::future::Future>::poll
             at ./src/common/src/util/debug/trace_context.rs:321:23
  71: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/future/future/fuse.rs:86:37
  72: risingwave_stream::executor::actor::Actor<C>::run::{{closure}}
             at ./src/stream/src/executor/actor.rs:166:16
  73: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  74: risingwave_stream::task::stream_manager::LocalStreamManagerCore::build_actors::{{closure}}
             at ./src/stream/src/task/stream_manager.rs:569:36
  75: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  76: risingwave_common::util::debug::trace_context::monitored::{{closure}}::{{closure}}::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/macros/select.rs:507:49
  77: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/future/poll_fn.rs:38:9
  78: risingwave_common::util::debug::trace_context::monitored::{{closure}}::{{closure}}
             at ./src/common/src/util/debug/trace_context.rs:389:17
  79: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  80: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/task/task_local.rs:345:35
  81: tokio::task::task_local::LocalKey<T>::scope_inner
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/task/task_local.rs:231:19
  82: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/task/task_local.rs:342:13
  83: risingwave_common::util::debug::trace_context::monitored::{{closure}}
             at ./src/common/src/util/debug/trace_context.rs:394:10
  84: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  85: <tokio_metrics::task::Instrumented<T> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-metrics-0.1.0/src/task.rs:2365:19
  86: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.35/src/instrument.rs:272:9
  87: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:165:17
  88: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/loom/std/unsafe_cell.rs:14:9
  89: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:155:13
  90: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:480:19
  91: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panic/unwind_safe.rs:271:9
  92: std::panicking::try::do_call
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
  93: std::panicking::try
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
  94: std::panic::catch_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panic.rs:137:14
  95: tokio::runtime::task::harness::poll_future
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:468:18
  96: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:104:27
  97: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:57:15
  98: tokio::runtime::task::raw::RawTask::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/raw.rs:84:18
  99: tokio::runtime::task::LocalNotified<S>::run
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/mod.rs:381:9
 100: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:435:13
 101: tokio::coop::with_budget::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:102:9
 102: std::thread::local::LocalKey<T>::try_with
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/thread/local.rs:445:16
 103: std::thread::local::LocalKey<T>::with
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/thread/local.rs:421:9
 104: tokio::coop::with_budget
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:434:9
 105: tokio::coop::budget
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/coop.rs:72:5
 106: tokio::runtime::thread_pool::worker::Context::run_task
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:434:9
 107: tokio::runtime::thread_pool::worker::Context::run
 108: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:386:17
 109: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/macros/scoped_tls.rs:61:9
 110: tokio::runtime::thread_pool::worker::run
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:383:5
 111: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:362:45
 112: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/task.rs:42:21
 113: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.35/src/instrument.rs:272:9
 114: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:165:17
 115: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/loom/std/unsafe_cell.rs:14:9
 116: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:155:13
 117: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:480:19
 118: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panic/unwind_safe.rs:271:9
 119: std::panicking::try::do_call
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
 120: std::panicking::try
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
 121: std::panic::catch_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panic.rs:137:14
 122: tokio::runtime::task::harness::poll_future
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:468:18
 123: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:104:27
 124: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:57:15
 125: tokio::runtime::task::raw::RawTask::poll
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/raw.rs:84:18
 126: tokio::runtime::task::UnownedTask<S>::run
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/mod.rs:418:9
 127: tokio::runtime::blocking::pool::Task::run
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/pool.rs:91:9
 128: tokio::runtime::blocking::pool::Inner::run
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/pool.rs:325:17
 129: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/bugenzhao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/blocking/pool.rs:300:13
 130: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/sys_common/backtrace.rs:122:18
 131: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/thread/mod.rs:505:17
 132: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panic/unwind_safe.rs:271:9
 133: std::panicking::try::do_call
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
 134: std::panicking::try
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
 135: std::panic::catch_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panic.rs:137:14
 136: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/thread/mod.rs:504:30
 137: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/ops/function.rs:248:5
 138: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/alloc/src/boxed.rs:1935:9
 139: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/alloc/src/boxed.rs:1935:9
 140: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/sys/unix/thread.rs:108:17
 141: __pthread_deallocate
```

**Comment by Little-Wallace** [comment]
@Li0k  I think we do not need to set timeout for the operation `get_compaction_group_id`.

**Comment by Li0k** [comment]
> @Li0k I think we do not need to set timeout for the operation `get_compaction_group_id`.

Yes, I think this kind of error that the upper layer can't handle(on the premise that the error can be exposed), we should keep retrying instead of returning failure

**Comment by Li0k** [comment]
Do we need a push-based implementation to avoid the meta access pressure caused by cache-miss when creating mv continuously.

The LocalCompactionGroupManager is maintained locally by the push update of notification_serivice, and the operator accesses the LocalCompactionGroupManager. Perhaps the logic of loop and timeout in the pull implementation can be eliminated through this

**Comment by zwang28** [comment]
Reproduced and found that all required compaction group info is actually fetched in one single RPC, and the RPC is fast too.
The timeout is caused by some waiters not get notified timely after the data is fetched. I think it's because the corresponding task not get scheduled.

```
                // Wait for other to fetch data via RPC
                let timer = Instant::now();
                notify.notified().await;
                let cost = timer.elapsed().as_millis();
                tracing::info!("wait for {} cost {} millis", table_id, cost);
                notify.notify_one();
```

```
compute-node-2  | 2022-08-09T13:53:06.467744Z  INFO risingwave_storage::hummock::compaction_group_client: update cost 0 millis
compute-node-2  | 2022-08-09T13:53:06.467846Z  INFO risingwave_storage::hummock::compaction_group_client: wait for 1003 cost 0 millis
compute-node-2  | 2022-08-09T13:53:06.467935Z  INFO risingwave_storage::hummock::compaction_group_client: wait for 1003 cost 0 millis
compute-node-2  | 2022-08-09T13:53:06.468181Z  INFO risingwave_storage::hummock::compaction_group_client: wait for 1003 cost 0 millis
compute-node-2  | 2022-08-09T13:53:06.469029Z  INFO risingwave_storage::hummock::compaction_group_client: wait for 1003 cost 1 millis
compute-node-2  | 2022-08-09T13:53:06.469115Z  INFO risingwave_storage::hummock::compaction_group_client: wait for 1003 cost 1 millis
compute-node-2  | 2022-08-09T13:53:22.353682Z  INFO risingwave_storage::hummock::compaction_group_client: wait for 1003 cost 15886 millis
compute-node-2  | 2022-08-09T13:53:25.622798Z  INFO risingwave_storage::hummock::compaction_group_client: wait for 1003 cost 19155 millis
compute-node-2  | 2022-08-09T13:53:34.427954Z  WARN risingwave_rpc_client::meta_client: Failed to send_heartbeat: timeout deadline has elapsed
```

From the last line we can see the heartbeat task timeout too.

**Comment by zwang28** [comment]
Will fix this issue by removing timeout.
The timeout is aim to spot bug such as waiting on a deleted table id. I'll replace it with a assertion.
