### ISSUE TITLE
storage: barrier manager panicked at `Hummock error: SST {} is invalid`

### ISSUE THREAD

**Issue by BugenZhao** [singularity-data/risingwave#4562]
Found when benchmarking with nexmark source. Since the connector source reader is busy generating messages, the heartbeat begins to timeout, and then the meta service deletes expired workers and finally panics. Is this caused by worker removal?

The configuration is the same as #4553.

```
2022-08-10T06:29:24.840569Z  WARN risingwave_meta::cluster: Deleted expired worker Worker {
    worker_node: WorkerNode {
        id: 1,
        r#type: ComputeNode,
        ...

thread 'tokio-runtime-worker' panicked at 'failed to execute barrier: Hummock error: SST 22 is invalid
  backtrace of `MetaError`:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/backtrace.rs:328:13
   3: <risingwave_meta::error::MetaError as core::convert::From<risingwave_meta::error::MetaErrorInner>>::from
             at ./src/meta/src/error.rs:52:33
   4: <T as core::convert::Into<U>>::into
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/convert/mod.rs:550:9
   5: <risingwave_meta::error::MetaError as core::convert::From<risingwave_meta::hummock::error::Error>>::from
             at ./src/meta/src/error.rs:94:9
   6: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/result.rs:2134:27
   7: risingwave_meta::barrier::GlobalBarrierManager<S>::complete_barriers::{{closure}}
             at ./src/meta/src/barrier/mod.rs:823:21
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   9: risingwave_meta::barrier::GlobalBarrierManager<S>::barrier_complete_and_commit::{{closure}}
             at ./src/meta/src/barrier/mod.rs:742:68
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  11: risingwave_meta::barrier::GlobalBarrierManager<S>::run::{{closure}}
             at ./src/meta/src/barrier/mod.rs:563:22
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  13: risingwave_meta::barrier::GlobalBarrierManager<S>::start::{{closure}}::{{closure}}
             at ./src/meta/src/barrier/mod.rs:511:45
```

**Comment by zwang28** [comment]
> Is this caused by worker removal?

Yes. Hummock meta will reject any "invalid SST" that is from a removed worker.

**Comment by zwang28** [comment]
Further more I'd like to add generation id for worker and reject any "invalid SST" from older generation. 
That is, if a worker is restarted before its heartbeat timeout, its worker id remains unchanged, but its generation id will increase.

**Comment by zwang28** [comment]
It panics only because we don't enable recovery https://github.com/singularity-data/risingwave/blob/8135a39585d6f5bfe9d58697165a9a3b1fd9ea1a/src/meta/src/barrier/mod.rs#L762

So is it OK to close this issue?

**Comment by BugenZhao** [comment]
Got it. Sounds okay to close this.
