### ISSUE TITLE
streaming: Top-N state table sanity check failed for `Update`

### ISSUE THREAD

**Issue by BugenZhao** [singularity-data/risingwave#4774]
```
thread 'tokio-runtime-worker' panicked at 'value mismatch when updating row: Some(Row([Some(Utf8("Customer#000000004")), Some(Int32(4)), Some(Int64(71)), Some(NaiveDate(NaiveDateWrapper(1998-01-24))), Some(Decimal(Normalized(178821.73))), Some(Decimal(Normalized(117)))])) != Row([Some(Utf8("Customer#000000004")), Some(Int32(4)), Some(Int64(71)), Some(NaiveDate(NaiveDateWrapper(1998-01-24))), Some(Decimal(Normalized(178821.73))), Some(Decimal(Normalized(154)))])', /risingwave/src/storage/src/table/storage_table.rs:529:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: risingwave_storage::table::storage_table::StorageTableBase<S,RS,_>::batch_write_rows::{{closure}}
             at ./src/storage/src/table/storage_table.rs:529:25
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   4: risingwave_storage::table::state_table::StateTableBase<S,RS>::commit::{{closure}}
             at ./src/storage/src/table/state_table.rs:188:52
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   6: risingwave_stream::executor::managed_state::top_n::top_n_state_new::ManagedTopNStateNew<S>::flush::{{closure}}
             at ./src/stream/src/executor/managed_state/top_n/top_n_state_new.rs:203:39
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   8: <risingwave_stream::executor::top_n::InnerTopNExecutorNew<S> as risingwave_stream::executor::top_n_executor::TopNExecutorBase>::flush_data::{{closure}}
             at ./src/stream/src/executor/top_n.rs:393:40
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/future.rs:124:9
  11: risingwave_stream::executor::top_n_executor::TopNExecutorWrapper<E>::top_n_executor_execute::{{closure}}
             at ./src/stream/src/executor/top_n_executor.rs:112:50
```

Full logs [here](https://buildkite.com/singularity-data/pull-request/builds/6453#0182c380-8bbe-4206-8140-28bebe144d01).

cc @skyzh @StrikeW

**Comment by fuyufjh** [comment]
I think @skyzh has gave up the sanity check for streaming operators, because many operators don't distinguish between `insert` and `replace`  e.g. https://github.com/singularity-data/risingwave/issues/3887

**Comment by BugenZhao** [comment]
> I think @skyzh has gave up the sanity check for streaming operators, because many operators don't distinguish between `insert` and `replace` e.g. #3887

The sanity check for the Top-N state worked well before, and this happens accidentally which looks strange. 🤔 And the backtrace shows that it's actually calling `Update`.

**Comment by BugenZhao** [comment]
Another reproduction: https://buildkite.com/singularity-data/pull-request/builds/6485#0182c481-1c7d-4bf5-b2a3-9e0d7877af03

**Comment by fuyufjh** [comment]
@Shmiwy Can you please take a look?

**Comment by st1page** [comment]
It is not easy to reproduce. I have checked the code and the internal table catalog of stream TopN. I think they are correct. And let's keep a close watch on the issue.

**Comment by BugenZhao** [comment]
Another reproduction:

https://buildkite.com/singularity-data/pull-request/builds/6640#0182cb06-8935-4554-8f80-81c1f1cfc7c1

**Comment by xxhZs** [comment]
It's the same as https://github.com/risingwavelabs/risingwave/issues/4861. So close it.
