### ISSUE TITLE
bug: NexMark Q16: panic: double insert

### ISSUE THREAD

**Issue by fuyufjh** [singularity-data/risingwave#4797]
**Describe the bug**

```sql 
CREATE TABLE bid (
    "auction" BIGINT,
    "bidder" BIGINT,
    "price" BIGINT,
    "channel" VARCHAR,
    "url" VARCHAR,
    "date_time" TIMESTAMP
);

INSERT INTO bid (
    auction,
    bidder,
    price,
    channel,
    url,
    date_time
) VALUES
(1000, 1001, 499920, 'Baidu', 'https://www.nexmark.com/zd_/npjz/ogs/item.htm?query=1', '2015-07-15 00:00:01.001'),
(1000, 1007, 12655, 'Facebook', 'https://www.nexmark.com/_ul/azrc/inum/item.htm?query=1', '2015-07-15 00:00:01.001'),
(1012, 1003, 19269, 'Facebook', 'https://www.nexmark.com/_ul/azrc/inum/item.htm?query=1', '2015-07-15 00:00:02.001'),
(1000, 1001, 43672280, 'channel-6682', 'https://www.nexmark.com/cyry/_el/yx_e/item.htm?query=1&channel_id=1482162176', '2015-07-15 00:03:00.001'),
(1000, 1010, 235, 'Facebook', 'https://www.nexmark.com/_ul/azrc/inum/item.htm?query=1', '2015-07-15 00:00:04.001'),
(1007, 1001, 242, 'channel-2928', 'https://www.nexmark.com/zgtz/wbr/swo/item.htm?query=1&channel_id=248512512', '2015-07-15 00:00:05.002'),
(1012, 1001, 71083760, 'channel-9838', 'https://www.nexmark.com/ima/wox/vzf/item.htm?query=1&channel_id=1986265088', '2015-07-15 00:00:06.002'),
(1009, 1001, 209960, 'Apple', 'https://www.nexmark.com/rch/jzb/lvhl/item.htm?query=1', '2015-07-15 00:00:07.002'),
(1003, 1001, 89027544, 'Google', 'https://www.nexmark.com/_w_/fgi/pqag/item.htm?query=1', '2015-07-15 00:00:08.002'),
(1000, 1002, 322, 'Facebook', 'https://www.nexmark.com/_ul/azrc/inum/item.htm?query=1', '2015-07-15 00:00:09.002'),
(1000, 1004, 2349, 'Google', 'https://www.nexmark.com/_w_/fgi/pqag/item.htm?query=1', '2015-07-15 00:00:10.003'),
(1011, 1001, 5255, 'Google', 'https://www.nexmark.com/_w_/fgi/pqag/item.htm?query=1', '2015-07-15 00:00:11.003'),
(1000, 1001, 13982877, 'Google', 'https://www.nexmark.com/_w_/fgi/pqag/item.htm?query=1', '2015-07-15 00:0:13.003'),
(1001, 1001, 84935, 'channel-7049', 'https://www.nexmark.com/hbc/xnmx/szt/item.htm?query=1&channel_id=1848115200', '2015-07-15 00:00:14.003'),
(1000, 1001, 28676694, 'Facebook', 'https://www.nexmark.com/_ul/azrc/inum/item.htm?query=1', '2015-07-15 00:00:15.003'),
(1000, 1001, 1930913, 'channel-227', 'https://www.nexmark.com/_fsw/agqs/jrt/item.htm?query=1&channel_id=956301312', '2015-07-15 00:00:16.004'),
(1000, 1001, 567581, 'channel-988', 'https://www.nexmark.com/_ge/ugl/muq/item.htm?query=1&channel_id=1002438656', '2015-07-15 00:00:16.004'),
(1010, 1001, 213, 'channel-5117', 'https://www.nexmark.com/pxt/bht/gtlo/item.htm?query=1&channel_id=1077411840', '2015-07-15 00:00:20.004'),
(1006, 1001, 21659600, 'Google', 'https://www.nexmark.com/_w_/fgi/pqag/item.htm?query=1', '2015-07-15 00:00:21.004'),
(1012, 1001, 170060, 'channel-20', 'https://www.nexmark.com/omkl/ceb/mnhp/item.htm?query=1&channel_id=671088640', '2015-07-15 00:00:22.004'),
(1010, 1002, 2092, 'Google', 'https://www.nexmark.com/dfds/kkg/ebn/item.htm?query=1', '2015-07-15 00:00:23.005');

CREATE MATERIALIZED VIEW nexmark_q16 AS
SELECT
    channel,
    to_char(date_time, 'YYYY-MM-DD') as "day",
    max(to_char(date_time, 'HH:mm')) as "minute",
    count(*) AS total_bids,
    count(*) filter (where price < 10000) AS rank1_bids,
    count(*) filter (where price >= 10000 and price < 1000000) AS rank2_bids,
    count(*) filter (where price >= 1000000) AS rank3_bids,
    count(distinct bidder) AS total_bidders,
    count(distinct bidder) filter (where price < 10000) AS rank1_bidders,
    count(distinct bidder) filter (where price >= 10000 and price < 1000000) AS rank2_bidders,
    count(distinct bidder) filter (where price >= 1000000) AS rank3_bidders,
    count(distinct auction) AS total_auctions,
    count(distinct auction) filter (where price < 10000) AS rank1_auctions,
    count(distinct auction) filter (where price >= 10000 and price < 1000000) AS rank2_auctions,
    count(distinct auction) filter (where price >= 1000000) AS rank3_auctions
FROM bid
GROUP BY channel, to_char(date_time, 'YYYY-MM-DD');
```

Crashed:

```
thread 'risingwave-streaming-actor' panicked at 'invalid flush status: double insert [0, 1, 70, 97, 99, 101, 98, 111, 111, 107, 8, 0, 1, 50, 48, 49, 53, 45, 48, 55, 45, 9, 49, 53, 0, 0, 0, 0, 0, 0, 2, 1, 1, 1, 1, 0, 128, 0, 0, 0, 0, 0, 3, 232, 0, 128, 0, 0, 0, 0, 0, 3, 232, 0, 128, 0, 0, 0, 0, 0, 3, 232, 0, 128, 0, 0, 0, 0, 0, 3, 232, 0, 128, 0, 0, 0, 0, 0, 0, 7, 254, 1, 0, 128, 0, 0, 0, 0, 0, 0, 7] -> Row([Some(Utf8("Facebook")), Some(Utf8("2015-07-15")), None, None, None, None, Some(Int64(1000)), Some(Int64(1000)), Some(Int64(1000)), Some(Int64(1000)), Some(Int64(7)), None, None, Some(Int64(7))])', src/storage/src/table/mem_table.rs:75:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: risingwave_storage::table::mem_table::MemTable::insert
             at ./src/storage/src/table/mem_table.rs:75:21
   3: risingwave_storage::table::state_table::StateTableBase<S,RS>::insert
             at ./src/storage/src/table/state_table.rs:159:9
   4: risingwave_stream::executor::managed_state::aggregation::extreme::GenericExtremeState<S>::apply_chunk_inner
             at ./src/stream/src/executor/managed_state/aggregation/extreme.rs:194:21
   5: <risingwave_stream::executor::managed_state::aggregation::extreme::GenericExtremeState<S> as risingwave_stream::executor::managed_state::aggregation::extreme::ManagedTableState<S>>::apply_chunk::{{closure}}
             at ./src/stream/src/executor/managed_state/aggregation/extreme.rs:261:9
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/future.rs:124:9
   8: risingwave_stream::executor::managed_state::aggregation::ManagedStateImpl<S>::apply_chunk::{{closure}}
             at ./src/stream/src/executor/managed_state/aggregation/mod.rs:151:79
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  10: risingwave_stream::executor::hash_agg::HashAggExecutor<K,S>::apply_chunk::{{closure}}
             at ./src/stream/src/executor/hash_agg.rs:302:91
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  12: risingwave_stream::executor::hash_agg::HashAggExecutor<K,S>::execute_inner::{{closure}}
             at ./src/stream/src/executor/hash_agg.rs:424:81
  13: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  14: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  15: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  16: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/mod.rs:1626:9
  17: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/next.rs:32:9
  18: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/minitrace-0.4.0/src/future.rs:118:19
  19: risingwave_stream::executor::debug::trace::trace::{{closure}}
             at ./src/stream/src/executor/debug/trace.rs:57:60
  20: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  21: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  22: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/mod.rs:1626:9
  23: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/next.rs:32:9
  24: <async_stack_trace::StackTraced<F> as core::future::future::Future>::poll
             at ./src/utils/async_stack_trace/src/lib.rs:172:23
  25: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/fuse.rs:86:37
  26: risingwave_stream::executor::debug::trace::stack_trace::{{closure}}
             at ./src/stream/src/executor/debug/trace.rs:120:70
  27: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  28: risingwave_stream::executor::debug::schema_check::schema_check::{{closure}}
             at ./src/stream/src/executor/debug/schema_check.rs:27:1
  29: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  30: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  31: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/mod.rs:1626:9
  32: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/next.rs:32:9
  33: risingwave_stream::executor::debug::epoch_check::epoch_check::{{closure}}
             at ./src/stream/src/executor/debug/epoch_check.rs:31:44
  34: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  35: risingwave_stream::executor::debug::update_check::update_check::{{closure}}
             at ./src/stream/src/executor/debug/update_check.rs:27:1
  36: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  37: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  38: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  39: risingwave_stream::executor::simple::SimpleExecutorWrapper<E>::execute_inner::{{closure}}
             at ./src/stream/src/executor/simple.rs:69:5
  40: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  41: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  42: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  43: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/mod.rs:1626:9
  44: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/next.rs:32:9
  45: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/minitrace-0.4.0/src/future.rs:118:19
  46: risingwave_stream::executor::debug::trace::trace::{{closure}}
             at ./src/stream/src/executor/debug/trace.rs:57:60
  47: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  48: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  49: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/mod.rs:1626:9
  50: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/next.rs:32:9
  51: <async_stack_trace::StackTraced<F> as core::future::future::Future>::poll
             at ./src/utils/async_stack_trace/src/lib.rs:172:23
  52: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/fuse.rs:86:37
  53: risingwave_stream::executor::debug::trace::stack_trace::{{closure}}
             at ./src/stream/src/executor/debug/trace.rs:120:70
  54: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  55: risingwave_stream::executor::debug::schema_check::schema_check::{{closure}}
             at ./src/stream/src/executor/debug/schema_check.rs:27:1
  56: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  57: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  58: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/mod.rs:1626:9
  59: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/next.rs:32:9
  60: risingwave_stream::executor::debug::epoch_check::epoch_check::{{closure}}
             at ./src/stream/src/executor/debug/epoch_check.rs:31:44
  61: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  62: risingwave_stream::executor::debug::update_check::update_check::{{closure}}
             at ./src/stream/src/executor/debug/update_check.rs:27:1
  63: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  64: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  65: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  66: <risingwave_stream::executor::dispatch::DispatchExecutor as risingwave_stream::executor::StreamConsumer>::execute::{{closure}}
             at ./src/stream/src/executor/dispatch.rs:257:9
  67: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  68: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  69: <&mut S as futures_core::stream::Stream>::poll_next
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:104:9
  70: <tokio_stream::stream_ext::next::Next<St> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-stream-0.1.9/src/stream_ext/next.rs:42:9
  71: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/minitrace-0.4.0/src/future.rs:118:19
  72: <async_stack_trace::StackTraced<F> as core::future::future::Future>::poll
             at ./src/utils/async_stack_trace/src/lib.rs:172:23
  73: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/fuse.rs:86:37
  74: risingwave_stream::executor::actor::Actor<C>::run::{{closure}}
             at ./src/stream/src/executor/actor.rs:111:16
  75: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  76: risingwave_stream::task::stream_manager::LocalStreamManagerCore::build_actors::{{closure}}
             at ./src/stream/src/task/stream_manager.rs:591:32
  77: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  78: async_stack_trace::manager::TraceReporter::trace::{{closure}}::{{closure}}::{{closure}}
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/macros/select.rs:507:49
  79: <tokio::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/future/poll_fn.rs:38:9
  80: async_stack_trace::manager::TraceReporter::trace::{{closure}}::{{closure}}
             at ./src/utils/async_stack_trace/src/manager.rs:99:21
  81: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  82: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll::{{closure}}
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/task/task_local.rs:345:35
  83: tokio::task::task_local::LocalKey<T>::scope_inner
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/task/task_local.rs:231:19
  84: <tokio::task::task_local::TaskLocalFuture<T,F> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/task/task_local.rs:342:13
  85: async_stack_trace::manager::TraceReporter::trace::{{closure}}
             at ./src/utils/async_stack_trace/src/manager.rs:105:14
  86: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  87: async_stack_trace::manager::TraceReporter::optional_trace::{{closure}}
             at ./src/utils/async_stack_trace/src/manager.rs:119:69
  88: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  89: <tokio_metrics::task::Instrumented<T> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-metrics-0.1.0/src/task.rs:2365:19
  90: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Signal: SIGABRT (signal SIGABRT)
```

**To Reproduce**

As above.

**Expected behavior**

**Additional context**

explain:

```
 StreamMaterialize { columns: [channel, day, minute, total_bids, rank1_bids, rank2_bids, rank3_bids, total_bidders, rank1_bidders, rank2_bidders, rank3_bidders, total_auctions, rank1_auctions, rank2_auctions, rank3_auctions], pk_columns: [channel, day] }
   StreamProject { exprs: [bid.channel, ToChar(bid.date_time, 'YYYY-MM-DD':Varchar), max(max(ToChar(bid.date_time, 'HH:mm':Varchar))) filter((flag = 0:Int64)), Coalesce(sum(count) filter((flag = 0:Int64)), 0:Int64), Coalesce(sum(count filter((bid.price < 10000:Int32))) filter((flag = 0:Int64)), 0:Int64), Coalesce(sum(count filter((bid.price >= 10000:Int32) AND (bid.price < 1000000:Int32))) filter((flag = 0:Int64)), 0:Int64), Coalesce(sum(count filter((bid.price >= 1000000:Int32))) filter((flag = 0:Int64)), 0:Int64), count(bid.bidder) filter((flag = 1:Int64)), count(bid.bidder) filter((count filter((bid.price < 10000:Int32)) > 0:Int64) AND (flag = 2:Int64)), count(bid.bidder) filter((count filter((bid.price >= 10000:Int32) AND (bid.price < 1000000:Int32)) > 0:Int64) AND (flag = 3:Int64)), count(bid.bidder) filter((count filter((bid.price >= 1000000:Int32)) > 0:Int64) AND (flag = 4:Int64)), count(bid.auction) filter((flag = 5:Int64)), count(bid.auction) filter((count filter((bid.price < 10000:Int32)) > 0:Int64) AND (flag = 6:Int64)), count(bid.auction) filter((count filter((bid.price >= 10000:Int32) AND (bid.price < 1000000:Int32)) > 0:Int64) AND (flag = 7:Int64)), count(bid.auction) filter((count filter((bid.price >= 1000000:Int32)) > 0:Int64) AND (flag = 8:Int64))] }
     StreamHashAgg { group_key: [bid.channel, ToChar(bid.date_time, 'YYYY-MM-DD':Varchar)], aggs: [count, max(max(ToChar(bid.date_time, 'HH:mm':Varchar))) filter((flag = 0:Int64)), sum(count) filter((flag = 0:Int64)), sum(count filter((bid.price < 10000:Int32))) filter((flag = 0:Int64)), sum(count filter((bid.price >= 10000:Int32) AND (bid.price < 1000000:Int32))) filter((flag = 0:Int64)), sum(count filter((bid.price >= 1000000:Int32))) filter((flag = 0:Int64)), count(bid.bidder) filter((flag = 1:Int64)), count(bid.bidder) filter((count filter((bid.price < 10000:Int32)) > 0:Int64) AND (flag = 2:Int64)), count(bid.bidder) filter((count filter((bid.price >= 10000:Int32) AND (bid.price < 1000000:Int32)) > 0:Int64) AND (flag = 3:Int64)), count(bid.bidder) filter((count filter((bid.price >= 1000000:Int32)) > 0:Int64) AND (flag = 4:Int64)), count(bid.auction) filter((flag = 5:Int64)), count(bid.auction) filter((count filter((bid.price < 10000:Int32)) > 0:Int64) AND (flag = 6:Int64)), count(bid.auction) filter((count filter((bid.price >= 10000:Int32) AND (bid.price < 1000000:Int32)) > 0:Int64) AND (flag = 7:Int64)), count(bid.auction) filter((count filter((bid.price >= 1000000:Int32)) > 0:Int64) AND (flag = 8:Int64))] }
       StreamExchange { dist: HashShard(bid.channel, ToChar(bid.date_time, 'YYYY-MM-DD':Varchar)) }
         StreamProject { exprs: [bid.channel, ToChar(bid.date_time, 'YYYY-MM-DD':Varchar), bid.bidder, bid.bidder, bid.bidder, bid.bidder, bid.auction, bid.auction, bid.auction, bid.auction, flag, max(ToChar(bid.date_time, 'HH:mm':Varchar)), count, count filter((bid.price < 10000:Int32)), count filter((bid.price >= 10000:Int32) AND (bid.price < 1000000:Int32)), count filter((bid.price >= 1000000:Int32)), count filter((bid.price < 10000:Int32)), count filter((bid.price >= 10000:Int32) AND (bid.price < 1000000:Int32)), count filter((bid.price >= 1000000:Int32)), count filter((bid.price < 10000:Int32)), count filter((bid.price >= 10000:Int32) AND (bid.price < 1000000:Int32)), count filter((bid.price >= 1000000:Int32))] }
           StreamHashAgg { group_key: [bid.channel, ToChar(bid.date_time, 'YYYY-MM-DD':Varchar), bid.bidder, bid.bidder, bid.bidder, bid.bidder, bid.auction, bid.auction, bid.auction, bid.auction, flag], aggs: [count, max(ToChar(bid.date_time, 'HH:mm':Varchar)), count, count filter((bid.price < 10000:Int32)), count filter((bid.price >= 10000:Int32) AND (bid.price < 1000000:Int32)), count filter((bid.price >= 1000000:Int32)), count filter((bid.price < 10000:Int32)), count filter((bid.price >= 10000:Int32) AND (bid.price < 1000000:Int32)), count filter((bid.price >= 1000000:Int32)), count filter((bid.price < 10000:Int32)), count filter((bid.price >= 10000:Int32) AND (bid.price < 1000000:Int32)), count filter((bid.price >= 1000000:Int32))] }
             StreamExchange { dist: HashShard(bid.channel, ToChar(bid.date_time, 'YYYY-MM-DD':Varchar), bid.bidder, bid.auction, flag) }
               StreamExpand { column_subsets: [[bid.channel, ToChar(bid.date_time, 'YYYY-MM-DD':Varchar), ToChar(bid.date_time, 'HH:mm':Varchar), bid.price], [bid.channel, ToChar(bid.date_time, 'YYYY-MM-DD':Varchar), bid.bidder], [bid.channel, ToChar(bid.date_time, 'YYYY-MM-DD':Varchar), bid.price, bid.bidder], [bid.channel, ToChar(bid.date_time, 'YYYY-MM-DD':Varchar), bid.price, bid.bidder], [bid.channel, ToChar(bid.date_time, 'YYYY-MM-DD':Varchar), bid.price, bid.bidder], [bid.channel, ToChar(bid.date_time, 'YYYY-MM-DD':Varchar), bid.auction], [bid.channel, ToChar(bid.date_time, 'YYYY-MM-DD':Varchar), bid.price, bid.auction], [bid.channel, ToChar(bid.date_time, 'YYYY-MM-DD':Varchar), bid.price, bid.auction], [bid.channel, ToChar(bid.date_time, 'YYYY-MM-DD':Varchar), bid.price, bid.auction]] }
                 StreamProject { exprs: [bid.channel, ToChar(bid.date_time, 'YYYY-MM-DD':Varchar), ToChar(bid.date_time, 'HH:mm':Varchar), bid.price, bid.bidder, bid.auction, bid._row_id] }
                   StreamTableScan { table: bid, columns: [auction, bidder, price, channel, date_time, _row_id] }
```

**Comment by fuyufjh** [comment]
@richardchien Can you please take a look?

**Comment by richardchien** [comment]
Narrowed the range to the following SQL:

```sql
CREATE MATERIALIZED VIEW nexmark_q16 AS
SELECT
    max(date_time) as max_dt,
    count(distinct bidder) AS total_bidders
FROM bid
GROUP BY channel;
```

and

```sql
CREATE MATERIALIZED VIEW nexmark_q16 AS
SELECT
    max(date_time) as max_dt,
    count(distinct bidder) AS total_bidders
FROM bid;
```

**Comment by st1page** [comment]
#3589 distinct agg in streaming is not ready yet

**Comment by fuyufjh** [comment]
related #132

NexMark Q16 blocks here. Please help to add the e2e test once fixed. Branch: [add_nexmark_q16](https://github.com/singularity-data/risingwave/compare/eric/add_nexmark_q16)
