### ISSUE TITLE
bug: panic at 'update check failed on `ProjectSet E00000033`: expect U+ after  U-

### ISSUE THREAD

**Issue by richardchien** [singularity-data/risingwave#4894]
### Describe the bug

panic log:

```
thread 'risingwave-streaming-actor' panicked at 'update check failed on `ProjectSet E00000033`: expect U+ after  U-:
 first row: Some([Some(Int64(0)), Some(Int32(1))])
second row: Some([Some(Int64(1)), Some(Int32(2))])', src/stream/src/executor/debug/update_check.rs:43:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panicking.rs:142:14
   2: risingwave_stream::executor::debug::update_check::update_check::{{closure}}
             at ./src/stream/src/executor/debug/update_check.rs:43:21
   3: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
   4: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
   5: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
   6: risingwave_stream::executor::simple::SimpleExecutorWrapper<E>::execute_inner::{{closure}}
             at ./src/stream/src/executor/simple.rs:69:5
   7: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
   8: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
   9: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  10: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/mod.rs:1626:9
  11: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/next.rs:32:9
  12: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/minitrace-0.4.0/src/future.rs:118:19
  13: risingwave_stream::executor::debug::trace::trace::{{closure}}
             at ./src/stream/src/executor/debug/trace.rs:57:60
  14: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  15: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  16: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/mod.rs:1626:9
  17: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/next.rs:32:9
  18: <async_stack_trace::StackTraced<F> as core::future::future::Future>::poll
             at ./src/utils/async_stack_trace/src/lib.rs:140:36
  19: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/fuse.rs:86:37
  20: risingwave_stream::executor::debug::trace::stack_trace::{{closure}}
             at ./src/stream/src/executor/debug/trace.rs:120:70
  21: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  22: risingwave_stream::executor::debug::schema_check::schema_check::{{closure}}
             at ./src/stream/src/executor/debug/schema_check.rs:27:1
  23: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  24: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  25: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/mod.rs:1626:9
  26: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/next.rs:32:9
  27: risingwave_stream::executor::debug::epoch_check::epoch_check::{{closure}}
             at ./src/stream/src/executor/debug/epoch_check.rs:31:44
  28: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  29: risingwave_stream::executor::debug::update_check::update_check::{{closure}}
             at ./src/stream/src/executor/debug/update_check.rs:27:1
  30: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  31: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  32: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  33: risingwave_stream::executor::mview::materialize::MaterializeExecutor<S>::execute_inner::{{closure}}
             at ./src/stream/src/executor/mview/materialize.rs:113:5
  34: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  35: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  36: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  37: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/mod.rs:1626:9
  38: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/next.rs:32:9
  39: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/minitrace-0.4.0/src/future.rs:118:19
  40: risingwave_stream::executor::debug::trace::trace::{{closure}}
             at ./src/stream/src/executor/debug/trace.rs:57:60
  41: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  42: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  43: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/mod.rs:1626:9
  44: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/next.rs:32:9
  45: <async_stack_trace::StackTraced<F> as core::future::future::Future>::poll
             at ./src/utils/async_stack_trace/src/lib.rs:140:36
  46: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/fuse.rs:86:37
  47: risingwave_stream::executor::debug::trace::stack_trace::{{closure}}
             at ./src/stream/src/executor/debug/trace.rs:120:70
  48: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  49: risingwave_stream::executor::debug::schema_check::schema_check::{{closure}}
             at ./src/stream/src/executor/debug/schema_check.rs:27:1
  50: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  51: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  52: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/mod.rs:1626:9
  53: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/stream/stream/next.rs:32:9
  54: risingwave_stream::executor::debug::epoch_check::epoch_check::{{closure}}
             at ./src/stream/src/executor/debug/epoch_check.rs:31:44
  55: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  56: risingwave_stream::executor::debug::update_check::update_check::{{closure}}
             at ./src/stream/src/executor/debug/update_check.rs:27:1
  57: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  58: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  59: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  60: <risingwave_stream::executor::dispatch::DispatchExecutor as risingwave_stream::executor::StreamConsumer>::execute::{{closure}}
             at ./src/stream/src/executor/dispatch.rs:257:9
  61: <futures_async_stream::try_stream::from_generator::GenTryStream<G> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-async-stream-0.2.5/src/lib.rs:430:31
  62: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:120:9
  63: <&mut S as futures_core::stream::Stream>::poll_next
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.23/src/stream.rs:104:9
  64: <tokio_stream::stream_ext::next::Next<St> as core::future::future::Future>::poll
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-stream-0.1.9/src/stream_ext/next.rs:42:9
  65: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/minitrace-0.4.0/src/future.rs:118:19
  66: <async_stack_trace::StackTraced<F> as core::future::future::Future>::poll
             at ./src/utils/async_stack_trace/src/lib.rs:140:36
  67: <futures_util::future::future::fuse::Fuse<Fut> as core::future::future::Future>::poll
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.23/src/future/future/fuse.rs:86:37
  68: risingwave_stream::executor::actor::Actor<C>::run::{{closure}}
             at ./src/stream/src/executor/actor.rs:111:16
  69: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  70: risingwave_stream::task::stream_manager::LocalStreamManagerCore::build_actors::{{closure}}
             at ./src/stream/src/task/stream_manager.rs:609:32
  71: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/future/mod.rs:91:19
  72: <risingwave_stream::task::stream_manager::LocalStreamManagerCore::build_actors::__Enum15994158506141524639<__Variant0,__Variant1> as core::future::future::Future>::poll
             at ./src/stream/src/task/stream_manager.rs:611:17
  73: <tokio_metrics::task::Instrumented<T> as core::future::future::Future>::poll
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-metrics-0.1.0/src/task.rs:2365:19
  74: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.36/src/instrument.rs:272:9
  75: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:165:17
  76: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/loom/std/unsafe_cell.rs:14:9
  77: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/core.rs:155:13
  78: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:480:19
  79: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/core/src/panic/unwind_safe.rs:271:9
  80: std::panicking::try::do_call
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:492:40
  81: ___rust_try
  82: std::panicking::try
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panicking.rs:456:19
  83: std::panic::catch_unwind
             at /rustc/9067d5277d10f0f32a49ec9c125a33828e26a32b/library/std/src/panic.rs:137:14
  84: tokio::runtime::task::harness::poll_future
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:468:18
  85: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:104:27
  86: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/harness.rs:57:15
  87: tokio::runtime::task::raw::poll
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/raw.rs:144:5
  88: tokio::runtime::task::raw::RawTask::poll
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/raw.rs:84:18
  89: tokio::runtime::task::LocalNotified<S>::run
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/task/mod.rs:381:9
  90: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /Users/richard/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.20.1/src/runtime/thread_pool/worker.rs:458:21
```

### To Reproduce

```sql
create table t (a varchar, b int, c int);
insert into t values ('aaa', 1, 1), ('bbb', 0, 2), ('ccc', 0, 5), ('ddd', 1, 4);

create materialized view mv1 as select array_agg(c) as res from t;
create materialized view mv2 as select u from (select unnest(res) from mv1) p(u) order by u;

select * from mv2;
# OK until now

insert into t values ('x', 1, 2), ('y', 3, 6); # Failed
```

### Expected behavior

Should successfully process the newly inserted values.

**Comment by xxchan** [comment]
A smaller reproduce:
```sql
dev=> create table t (c int);
create materialized view mv1 as select array_agg(c) as res from t;
create materialized view mv2 as select res as u from mv1;

dev=> insert into t values (1),(2); 

dev=> insert into t values (3);
```

**Comment by xxchan** [comment]
I think this is expected behavior for `ProjectSet`...
```
input:
U- [1,2]
U+ [1,2,3]

output:
U- 1
U- 2
U+ 1
U+ 2
U+ 3
```

To be more general:
```
input:
op1 row1
op2 row2

output:
op1 row1-1
op1 row1-2
op1 row1-3
op2 row2-1
op2 row2-2
```

So `ProjectSet` will break the assumption that `U+` always follows `U-`. What's more, it will break this assumption for its downstream executors..

**Comment by xxchan** [comment]
cc @BugenZhao Any ideas? 🥵

**Comment by skyzh** [comment]
Then let's just rewrite to insert / delete for project set. That's what we've done in LookupJoin.

**Comment by skyzh** [comment]
... and HashJoin.

**Comment by BugenZhao** [comment]
Agree. May adapt the fix of https://github.com/singularity-data/risingwave/pull/1811.

**Comment by xxchan** [comment]
> - or reorder the `U-` `U+` into groups?

Not possible. There may have different numbers of `U-` and `U+`.
