### ISSUE TITLE
NPE for IN expression with non-literal children

### ISSUE THREAD

**Issue by xxchan** [singularity-data/risingwave#598]
https://github.com/singularity-data/risingwave-dev/issues/590 

Actually we support this feature currently, because the `IN` expression will be optimized to `OR`

```sql
create table t2 (v1 int, v2 int, v3 int);
insert into t2 values (1,1,1), (-1,1,1), (2,3,4);   
explain select * from t2 where v1 in (v3, 2);
```

```
 RwBatchExchange(distribution=[RwDistributionTrait{type=SINGLETON, keys=[]}], collation=[[]])
   RwBatchFilter(condition=[OR(=($0, $2), =($0, 2))])
     RwBatchScan(table=[[main, t2]], columns=[v1,v2,v3])
(3 rows)
```

When the list becomes longer (20 elems), it is not optimized
```sql
explain select * from t2 where v1 in (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20);
```
```                                                                                                     
 RwBatchExchange(distribution=[RwDistributionTrait{type=SINGLETON, keys=[]}], collation=[[]])
   RwBatchProject(v1=[$0], v2=[$1], v3=[$2])
     RwBatchHashJoin(condition=[=($0, $3)], joinType=[inner])
       RwBatchExchange(distribution=[RwDistributionTrait{type=HASH_DISTRIBUTED, keys=[0]}], collation=[[]])
         RwBatchScan(table=[[main, t2]], columns=[v1,v2,v3])
       RwBatchHashAgg(group=[{0}])
         RwBatchExchange(distribution=[RwDistributionTrait{type=HASH_DISTRIBUTED, keys=[0]}], collation=[[]])
           RwBatchHashAgg(group=[{0}])
             RwBatchValues(tuples=[[{ 1 }, { 2 }, { 3 }, { 4 }, { 5 }, { 6 }, { 7 }, { 8 }, { 9 }, { 10 }, { 11 }, { 12 }, { 13 }, { 14 }, { 15 }, { 16 }, { 17 }, { 18 }, { 19 }, { 20 }]])
(9 rows)
```
But now adding a non-literal item, we have NPE
```sql
 explain select * from t2 where v1 in (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,v3);
ERROR:  java.lang.NullPointerException: scope
```

```
com.risingwave.common.exception.PgException: java.lang.NullPointerException: scope
	at com.risingwave.common.exception.PgException.from(PgException.java:51)
	at com.risingwave.pgserver.database.RisingWaveDatabase.runStatement(RisingWaveDatabase.kt:31)
	at com.risingwave.pgwire.StateMachine.processQuery(StateMachine.kt:92)
	at com.risingwave.pgwire.StateMachine.process(StateMachine.kt:45)
	at com.risingwave.pgwire.PgProtocol.doProcess(PgProtocol.kt:49)
	at com.risingwave.pgwire.PgProtocol.access$doProcess(PgProtocol.kt:17)
	at com.risingwave.pgwire.PgProtocol$doProcess$1.invokeSuspend(PgProtocol.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.risingwave.pgwire.PgServer.serve(PgServer.kt:23)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: scope
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at org.apache.calcite.sql2rel.SqlToRelConverter$Blackboard.scope(SqlToRelConverter.java:4570)
	at org.apache.calcite.sql2rel.SqlToRelConverter$Blackboard.lookupExp(SqlToRelConverter.java:4783)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertIdentifier(SqlToRelConverter.java:4097)
	at org.apache.calcite.sql2rel.SqlToRelConverter.access$2500(SqlToRelConverter.java:223)
	at org.apache.calcite.sql2rel.SqlToRelConverter$Blackboard.visit(SqlToRelConverter.java:5278)
	at org.apache.calcite.sql2rel.SqlToRelConverter$Blackboard.visit(SqlToRelConverter.java:4495)
	at org.apache.calcite.sql.SqlIdentifier.accept(SqlIdentifier.java:325)
	at org.apache.calcite.sql2rel.SqlToRelConverter$Blackboard.convertExpression(SqlToRelConverter.java:5097)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertMultisets(SqlToRelConverter.java:4261)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertRowConstructor(SqlToRelConverter.java:4170)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertRowValues(SqlToRelConverter.java:1739)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQueryOrInList(SqlToRelConverter.java:1654)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertExists(SqlToRelConverter.java:1636)
	at org.apache.calcite.sql2rel.SqlToRelConverter.substituteSubQuery(SqlToRelConverter.java:1197)
	at org.apache.calcite.sql2rel.SqlToRelConverter.replaceSubQueries(SqlToRelConverter.java:1090)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertWhere(SqlToRelConverter.java:1056)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelectImpl(SqlToRelConverter.java:685)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertSelect(SqlToRelConverter.java:663)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQueryRecursive(SqlToRelConverter.java:3535)
	at org.apache.calcite.sql2rel.SqlToRelConverter.convertQuery(SqlToRelConverter.java:588)
	at com.risingwave.planner.sql.SqlConverter.toRel(SqlConverter.java:37)
	at com.risingwave.planner.planner.batch.BatchPlanner.plan(BatchPlanner.java:54)
	at com.risingwave.planner.planner.batch.BatchPlanner.planDistributed(BatchPlanner.java:85)
	at com.risingwave.planner.planner.batch.BatchPlanner.plan(BatchPlanner.java:49)
	at com.risingwave.execution.handler.ExplainHandler.optimize(ExplainHandler.java:55)
	at com.risingwave.execution.handler.ExplainHandler.handle(ExplainHandler.java:32)
	at com.risingwave.pgserver.database.QueryExecution.call(QueryExecution.java:23)
	at com.risingwave.pgserver.database.RisingWaveDatabase.runStatement(RisingWaveDatabase.kt:29)
	... 15 common frames omitted
```

**Comment by xxchan** [comment]
Close it since java frontend is deprecated
